// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'map': string;
  'map-container': string;
  'polygon-name': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
