// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'adjudication-phase': string;
  'blink': string;
  'ended': string;
  'flex-content-wrapper': string;
  'highlight': string;
  'info-helper': string;
  'info-phase-label': string;
  'not-initiated': string;
  'time-left': string;
  'turn-info-phase': string;
  'turn-info-remaining': string;
  'turn-progression-ui': string;
  'warning': string;
  'turn-phase-group': string;
  'turn': string;
  'phase': string;
  'divider': string;
  'time': string;
}
export const cssExports: CssExports;
export default cssExports;
