// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inner': string;
  'map-bar': string;
  'open': string;
  'toggle': string;
}
export const cssExports: CssExports;
export default cssExports;
