// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'iconbase': string;
  'map-icon': string;
  'pulse': string;
  'selected': string;
  'cluster': string
}
export const cssExports: CssExports;
export default cssExports;
