// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'iconbase': string;
  'map-icon': string;
  'pulse': string;
  'mycluster': string;
  'circle': string;
  'yellow': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
