// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dots': string;
  'key': string;
  'main': string;
  'password-mask': string;
}
export const cssExports: CssExports;
export default cssExports;
