// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'infoCard': string;
  'header': string;
  'content': string;
  'toggleDisplayMode': string;
}
export const cssExports: CssExports;
export default cssExports;
