// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accordion': string;
  'accordion-header': string;
  'accordion-title': string;
  'arrow-icon': string;
  'col': string;
  'role': string;
  'role-item': string;
  'role-title': string;
  'row': string;
  'section': string;
  'title-center': string;
}
export const cssExports: CssExports;
export default cssExports;
