// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string
  'complete': string
  'indicator': string
  'progress': string
  'scale': string
}
export const cssExports: CssExports
export default cssExports
