// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badges-box': string;
  'chat-inner-bubble': string;
  'chat-messgae-bubble': string;
  'chat-messgae-bubble-sent': string;
  'icon-private': string;
  'info-badge': string;
  'info-body': string;
  'message-item-unread': string;
  'message-title': string;
  'message-title-opened': string;
  'message-title-wrap': string;
  'private-message': string;
  'private-message-box': string;
  'private-message-text': string;
}
export const cssExports: CssExports;
export default cssExports;
