// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'fieldset': string;
  'form-headr': string;
  'visibility': string;
}
export const cssExports: CssExports;
export default cssExports;
