// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropzone-content': string;
  'icon': string;
  'main': string;
  'modal': string;
  'modal-bg': string;
  'modal-content': string;
}
export const cssExports: CssExports;
export default cssExports;
