// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'color': string;
  'cover': string;
  'popover': string;
  'swatch': string;
}
export const cssExports: CssExports;
export default cssExports;
