import React from 'react'
import { ForceData, MessageMap, PlayerUi, Role } from '@serge/custom-types'
import { FORCE_LAYDOWN, PERCEPTION_OF_CONTACT, STATE_OF_WORLD, SUBMIT_PLANS, VISIBILITY_CHANGES } from '@serge/config'
import { sendMapMessage } from '@serge/helpers'
import { TabNode } from 'flexlayout-react'
import { saveMapMessage } from '../../../ActionsAndReducers/playerUi/playerUi_ActionCreators'
import { Mapping, Assets, HexGrid, DataTable, Badge, RfiForm } from '@serge/components'
import _ from 'lodash'
import Channel from '../../../Components/Channel'
import findChannelByName from './findChannelByName'

const LocalTileLayer = {
  url: './tiles/{z}/{x}/{y}.png',
  attribution: 'Generated by QTiles'
}

const bounds = {
  imageTop: 14.194809302,
  imageLeft: 42.3558566271,
  imageRight: 43.7417816271,
  imageBottom: 12.401259302
}

type Factory = (node: TabNode) => React.ReactNode

/** utility to find the role for this role name */
const findRole = (roleName: string, forceData: ForceData | undefined): Role => {
  if(forceData) {
    const role = forceData.roles.find((role: Role) => role.name === roleName)
    if(role) {
      return role
    }
  }
  throw new Error('Role not found for:' + roleName);
}

const factory = (state: PlayerUi): Factory => {
  const mapPostBack = (form: string, payload: MessageMap, channelID: string): void => {
    switch(form) {
      case FORCE_LAYDOWN:
        sendMapMessage(FORCE_LAYDOWN, payload, state.selectedForce, channelID, state.selectedRole, state.currentWargame, saveMapMessage)
        break
      case VISIBILITY_CHANGES:
        sendMapMessage(VISIBILITY_CHANGES, payload, state.selectedForce, channelID, state.selectedRole, state.currentWargame, saveMapMessage)
        break
      case PERCEPTION_OF_CONTACT:
        sendMapMessage(PERCEPTION_OF_CONTACT, payload, state.selectedForce, channelID, state.selectedRole, state.currentWargame, saveMapMessage)
        break
      case SUBMIT_PLANS:
        sendMapMessage(SUBMIT_PLANS, payload, state.selectedForce, channelID, state.selectedRole, state.currentWargame, saveMapMessage)
        break
      case STATE_OF_WORLD:
        sendMapMessage(STATE_OF_WORLD, payload, state.selectedForce, channelID, state.selectedRole, state.currentWargame, saveMapMessage)
        break
        default:
      console.log('Handler not created for', form)
    }
  }

  return (node: TabNode): React.ReactNode => {
    // sort out if role can submit orders
    const role: Role = findRole(state.selectedRole, state.selectedForce)
    const canSubmitOrders: boolean = !!role.canSubmitPlans

    // Render the map
    const renderMap = (channelid: string) => <Mapping
        tileDiameterMins={5}
        bounds={bounds}
        tileLayer={LocalTileLayer}
        forces={state.allForces}
        platforms={state.allPlatformTypes}
        phase={state.phase}
        turnNumber={state.currentTurn}
        playerForce={state.selectedForce ? state.selectedForce.uniqid : ''}
        canSubmitOrders={canSubmitOrders}
        channelID = {channelid}
        mapPostBack={mapPostBack}
    >
      <Assets />
      <HexGrid/>
    </Mapping>

    // Render the RFI Data Table
    const renderRfiDataTable = () => {
      const dataTableProps = {
        columns: [
          'ID',
          {
            filters: [
              'Red Support',
              'Blue Support'
            ],
            label: 'Channel'
          },
          {
            filters: [
              'CO',
              'Logistic'
            ],
            label: 'From'
          },
          'Title',
          {
            filters: [
              'Unallocated',
              'In Progress',
              'Pending Review',
              'Released'
            ],
            label: 'Status'
          },
          {
            filters: [
              'Fuel specialist',
              'Aeronautic specialist',
              'Weapons specialist'
            ],
            label: 'Owner'
          }
        ],
        data: [
          ['RFI-red-33', 'Red Support', 'CO', 'Request for air support', 'Unallocated', ''],
          ['RFI-red-32', 'Red Support', 'Logistic', 'Fuel availability', 'In Progress', 'Fuel specialist'],
          ['RFI-red-28', 'Blue Support', 'Logistic', 'Air drop', 'Pending Review', 'Aeronautic specialist'],
          ['RFI-red-27', 'Blue Support', 'CO', 'Weapon authorization', 'Released', 'Weapons specialist']
        ].map((row): any => {
          const [id, channel, role, content, status, owner] = row
          const roleColors = {
            'Red Support': '#F94248',
            'Blue Support': '#00A3DE'
          }
          const statusColors = {
            Unallocated: '#B10303',
            'In Progress': '#E7740A',
            'Pending Review': '#434343',
            Released: '#007219'
          }
          return {
            collapsible: (
              <RfiForm request={{ title: 'Some title', description: 'Some description' }} />
            ),
            cells: [
              id,
              channel,
              {
                component: <Badge customBackgroundColor={roleColors[channel]} label={role}/>,
                label: role
              },
              content,
              {
                component: <Badge customBackgroundColor={statusColors[status]} customSize="large" label={status}/>,
                label: status
              },
              {
                component: owner ? <Badge customBackgroundColor="#434343" label={owner}/> : null,
                label: owner
              }
            ]
          }
        })
      }

      return (
        <DataTable {...dataTableProps} />
      )
    }

    if (_.isEmpty(state.channels)) return
    const channelsArray = Object.entries(state.channels)
    if (channelsArray.length === 1) {
      const isOnlyMap = channelsArray.find(entry => entry[1].name.toLowerCase() === 'mapping')
      if (isOnlyMap) {
        return renderMap('map')
      } else {
        return <Channel channelId={channelsArray[0][0]} />
      }
    } else {
      const matchedChannel = findChannelByName(state.channels, node.getName())
      const channelName = node.getName().toLowerCase()
      if (channelName === 'mapping') {
        // return <Mapping currentTurn={state.currentTurn} role={state.selectedRole} currentWargame={state.currentWargame} selectedForce={state.selectedForce} allForces={state.allForces} allPlatforms={state.allPlatformTypes} phase={state.phase} channelID={node._attributes.id} imageTop={imageTop} imageBottom={imageBottom} imageLeft={imageLeft} imageRight={imageRight}></Mapping>
        // _attributes.id
        return renderMap(node.getId())
      } else if (channelName === 'rfis') {
        return renderRfiDataTable()
      }
      return matchedChannel && matchedChannel.length ? <Channel channelId={matchedChannel[0]} /> : null
    }
  }
}

export default factory
