// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'searchlist-icon': string;
  'searchlist-menu': string;
  'searchlist-row': string;
}
export const cssExports: CssExports;
export default cssExports;
