// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'color-box': string;
  'input-container': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
