// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'box': string;
  'col': string;
  'control-groups': string;
  'message-content': string;
  'message-group': string;
  'message-title': string;
  'pager': string;
  'row': string;
  'section': string;
  'status-item': string;
  'table': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
