// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'box': string;
  'col': string;
  'control-groups': string;
  'message-content': string;
  'message-group': string;
  'message-title': string;
  'pager': string;
  'row': string;
  'section': string;
  'status-item': string;
  'table': string;
  'title': string;
  'mapping-item-constraints': string;
  'input': string;
  'constraints-icon': string;
  'constraints-cell': string;
  'cell-lbl': string;
  'accordion-header': string;
  'arrow-icon': string;
  'accordion': string;
  'accordion-details': string;
}
export const cssExports: CssExports;
export default cssExports;
