import React from 'react'

// Import component files
import VisibilityForm from './index'
import docs from './README.md'

/* Import mock data */
import { forces, platformTypes, selectedAsset } from '@serge/mocks'
import Mapping from '../mapping'

// import data types
import { Phase } from '@serge/config'
import collateVisibilityFormData from '../map-bar/helpers/collate-visibility-form-data'

export default {
  title: 'local/VisibilityForm',
  component: VisibilityForm,
  decorators: [],
  parameters: {
    readme: {
      // Show readme before story
      content: docs
    },
    options: {
      // We have no addons enabled in this story, so the addon panel should be hidden
      showPanel: false
    }
  }
}

// put in the post handler
const postback = (messageType: string, payload: any): void => {
  console.log('postback', messageType, payload)
}

const bounds = {
  imageTop: 14.194809302,
  imageLeft: 42.3558566271,
  imageRight: 43.7417816271,
  imageBottom: 12.401259302
}

const LocalTileLayer = {
  url: './tiles/{z}/{x}/{y}.png',
  attribution: 'Generated by QTiles'
}

const formData = collateVisibilityFormData(selectedAsset, forces)
const iconData = { platformType: 'merchant-vessel', forceColor: 'blue' }

// TODO: Add some state handling here
export const Default: React.FC = () => <Mapping
  tileDiameterMins={5}
  bounds={bounds}
  tileLayer={LocalTileLayer}
  forces={forces}
  playerForce='Blue'
  canSubmitOrders = {true}
  platforms={platformTypes}
  phase={Phase.Adjudication}
  turnNumber={5}
>
  <VisibilityForm postBack={postback} icon={iconData} formHeader="Visibility header" formData={formData} />
</Mapping>
