// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disable-offset': string;
  'input-container': string;
}
export const cssExports: CssExports;
export default cssExports;
