import L from 'leaflet'
import React from 'react'
import { Story } from '@storybook/react/types-6-0'

/* Import mock data */
import { forces, platformTypes } from '@serge/mocks'

// Import component files
import Mapping from './index'
import MappingPropTypes from './types/props'
import docs from './README.md'
import Assets from '../assets'
import { HexGrid } from '../hex-grid'

// import data types
import { Phase } from '@serge/config'

const wrapper: React.FC = (storyFn: any) => <div style={{ height: '700px' }}>{storyFn()}</div>

export default {
  title: 'local/AtlanticMapping',
  component: Mapping,
  decorators: [wrapper],
  parameters: {
    readme: {
      // Show readme before story
      content: docs
    },
    options: {
      // We have no addons enabled in this story, so the addon panel should be hidden
      showPanel: true
    },
    controls: {
      expanded: true
    }
  },
  argTypes: {
    playerForce: {
      name: 'View as',
      control: {
        type: 'radio',
        defaultValue: 'Blue',
        options: [
          'White',
          'Blue',
          'Red'
        ]
      }
    },
    phase: {
      name: 'Game phase',
      control: {
        type: 'radio',
        defaultValue: Phase.Planning,
        options: [
          Phase.Planning,
          Phase.Adjudication
        ]
      }
    },
    wargameInitiated: {
      name: 'Wargame has been initiated',
      control: {
        type: 'boolean'
      }
    },
    children: {
      table: {
        disable: true
      }
    }
  }
}

const bounds = L.latLngBounds([[80, -50.0], [40.0, 45]])

const LocalTileLayer = {
  url: './atlantic_tiles/{z}/{x}/{y}.png',
  attribution: 'Generated by QTiles'
}

const OSMTileLayer = {
  url: 'https://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png',
  attribution: 'Data © <a href="http://osm.org/copyright">OpenStreetMap</a>'
}

interface StoryPropTypes extends MappingPropTypes {
  showAllowableCells?: boolean
  allowableOrigin?: string
  allowableTerrain?: string
}

const Template: Story<StoryPropTypes> = (args) => {
  const {
    playerForce,
    ...props
  } = args
  const forceNames = {
    White: 'umpire',
    Blue: 'Blue',
    Red: 'Red'
  }
  return (
    <Mapping
      playerForce={forceNames[playerForce]}
      {...props}
    />
  )
}

/**
 * DEFAULT VIEW
 */
export const Default = Template
Default.args = {
  bounds: bounds,
  forces: forces,
  playerForce: 'Blue',
  canSubmitOrders: false,
  platforms: platformTypes,
  phase: Phase.Planning,
  turnNumber: 5,
  mapBar: false
}

export const NaturalEarth = Template
NaturalEarth.args = {
  bounds: bounds,
  tileLayer: LocalTileLayer,
  forces: forces,
  platforms: platformTypes,
  turnNumber: 2,
  children: (
    <>
      <HexGrid />
      <Assets />
    </>
  )
}

export const OpenStreetMap = Template
OpenStreetMap.args = {
  tileDiameterMins: 5,
  bounds: bounds,
  tileLayer: OSMTileLayer,
  forces: forces,
  platforms: platformTypes,
  turnNumber: 2,
  children: (
    <>
      <Assets />
      <HexGrid />
    </>
  )
}
