/* global it expect */

import React from 'react'
import { mount } from 'enzyme'

import Mapping from './index'

const bounds = {
  imageTop: 14.194809302,
  imageLeft: 42.3558566271,
  imageRight: 43.7417816271,
  imageBottom: 12.401259302
}

const LocalTileLayer = {
  url: '/tiles/{z}/{x}/{y}.png',
  attribution: 'Generated by QTiles'
}

it('Mapping renders correctly', () => {
  const div = document.createElement('div')
  document.body.appendChild(div)

  const tree = mount(<Mapping
    bounds = {bounds}
    tileLayer = {LocalTileLayer}
  />, { attachTo: div })

  expect(tree).toMatchSnapshot()
})
