import React from 'react'

// Import component files
import Mapping from './index'
import docs from './README.md'

export default {
  title: 'local/Mapping',
  component: Mapping,
  decorators: [],
  parameters: {
    readme: {
      // Show readme before story
      content: docs
    }
  }
}

const bounds = {
  imageTop: 14.194809302,
  imageLeft: 42.3558566271,
  imageRight: 43.7417816271,
  imageBottom: 12.401259302
}

const tileLayer = {
  url: '/tiles/{z}/{x}/{y}.png',
  attribution: 'Generated by QTiles'
}

export const Default: React.FunctionComponent = () => <Mapping
  bounds = {bounds}
  tileLayer = {tileLayer}
/>
