import L from 'leaflet'
import React from 'react'
import { Story } from '@storybook/react/types-6-0'

/* Import mock data */
import { forces, platformTypes } from '@serge/mocks'

// Import component files
import Mapping from './index'
import MappingPropTypes from './types/props'
import docs from './README.md'
import Assets from '../assets'
import { HexGrid } from '../hex-grid'

// import data types
import { Phase } from '@serge/config'
import { MessageMap } from '@serge/custom-types'

const wrapper: React.FC = (storyFn: any) => <div style={{ height: '700px' }}>{storyFn()}</div>

export default {
  title: 'local/AtlanticMapping',
  component: Mapping,
  decorators: [wrapper],
  parameters: {
    readme: {
      // Show readme before story
      content: docs
    },
    options: {
      // We have no addons enabled in this story, so the addon panel should be hidden
      showPanel: true
    },
    controls: {
      expanded: true
    }
  },
  argTypes: {
    zoom: {
      control: {
        type: 'number'
      }
    },
    playerForce: {
      name: 'View as',
      control: {
        type: 'radio',
        defaultValue: 'Blue',
        options: [
          'White',
          'Blue',
          'Red'
        ]
      }
    },
    phase: {
      name: 'Game phase',
      control: {
        type: 'radio',
        defaultValue: Phase.Planning,
        options: [
          Phase.Planning,
          Phase.Adjudication
        ]
      }
    },
    tileDiameterMins: {
      name: 'Tile diameter, nm',
      control: {
        type: 'range',
        defaultValue: 5,
        min: 1,
        max: 15,
        step: 1
      }
    },
    planningRangeProp: {
      name: 'Platform range',
      control: {
        type: 'range',
        defaultValue: 1,
        min: 1,
        max: 6,
        step: 1
      }
    },
    wargameInitiated: {
      name: 'Wargame has been initiated',
      control: {
        type: 'boolean'
      }
    },
    showAllowableCells: {
      name: 'Show allowable cells',
      control: {
        type: 'boolean'
      }
    },
    allowableOrigin: {
      name: 'Current location'
    },
    allowableTerrain: {
      name: 'Platform terrain constraints',
      defaultValue: 'Sea',
      control: {
        type: 'radio',
        options: [
          'Sea',
          'Land',
          'Air'
        ]
      }
    },
    children: {
      table: {
        disable: true
      }
    }
  }
}

const bounds = L.latLngBounds([[80, -50.0], [40.0, 45]])

const LocalTileLayer = {
  url: './atlantic_tiles/{z}/{x}/{y}.png',
  attribution: 'Generated by QTiles'
}

const OSMTileLayer = {
  url: 'https://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png',
  attribution: 'Data © <a href="http://osm.org/copyright">OpenStreetMap</a>'
}

interface StoryPropTypes extends MappingPropTypes {
  showAllowableCells?: boolean
  allowableOrigin?: string
  allowableTerrain?: string
}

const Template: Story<StoryPropTypes> = (args) => {
  const {
    playerForce,
    showAllowableCells,
    allowableOrigin = '',
    allowableTerrain = '',
    ...props
  } = args
  const forceNames = {
    White: 'umpire',
    Blue: 'Blue',
    Red: 'Red'
  }
  if (showAllowableCells) {
    props.planningConstraintsProp = {
      origin: allowableOrigin,
      travelMode: allowableTerrain,
      status: 'Transiting',
      speed: 20
    }
  }

  return (
    <Mapping
      playerForce={forceNames[playerForce]}
      {...props}
    />
  )
}

/**
 * DEFAULT VIEW
 */
export const Default = Template
Default.args = {
  tileDiameterMins: 5,
  bounds: bounds,
  tileLayer: LocalTileLayer,
  forces: forces,
  playerForce: 'Blue',
  canSubmitOrders: false,
  platforms: platformTypes,
  phase: Phase.Planning,
  turnNumber: 5,
  mapBar: false
}


// generic postback handler, for forms
const mapPostBack = (messageType: string, payload: MessageMap): void => {
  console.log('postback', messageType, payload)
  window.alert('postback:' + messageType + ', ' + JSON.stringify(payload))
}
export const NaturalEarth = Template
NaturalEarth.args = {
  tileDiameterMins: 5,
  bounds: bounds,
  tileLayer: LocalTileLayer,
  forces: forces,
  platforms: platformTypes,
  turnNumber: 2,
  mapPostBack: mapPostBack,
  children: (
    <>
      <Assets />
      <HexGrid />
    </>
  )
}

  export const OpenStreetMap = Template
  OpenStreetMap.args = {
  tileDiameterMins: 5,
  bounds: bounds,
  tileLayer: OSMTileLayer,
  forces: forces,
  platforms: platformTypes,
  turnNumber: 2,
  mapPostBack: mapPostBack,
  children: (
    <>
      <Assets />
      <HexGrid />
    </>
  )
}
