import React from 'react'

// Import component files
import Mapping from './index'
import docs from './README.md'

export default {
  title: 'local/Mapping',
  component: Mapping,
  decorators: [],
  parameters: {
    readme: {
      // Show readme before story
      content: docs
    }
  }
}

const bounds = {
  imageTop: 14.194809302,
  imageLeft: 42.3558566271,
  imageRight: 43.7417816271,
  imageBottom: 12.401259302
}

const tileLayer = {
  url: '/tiles/{z}/{x}/{y}.png',
  attribution: 'Generated by QTiles'
}

export const Default: React.FunctionComponent = () => <Mapping
  position = {[(bounds.imageTop + bounds.imageBottom) / 2, (bounds.imageLeft + bounds.imageRight) / 2]}
  minZoom = {8}
  maxZoom = {12}
  touchZoom = {true}
  zoom = {10}
  zoomDelta = {0.25}
  zoomSnap = {0.25}
  zoomControl = {false}
  attributionControl = {false}
  zoomAnimation = {false}
  tileLayer = {tileLayer} />
