import React from 'react'
import { Story } from '@storybook/react/types-6-0'
import { deepCopy } from '@serge/helpers'
import { MappingConstraints } from '@serge/custom-types'

// Import component files
import Mapping from './index'
import MappingPropTypes from './types/props'
import docs from './README.md'
import Assets from '../assets'
import { HexGrid } from '../hex-grid'

// import data types
import { Domain, Phase, serverPath } from '@serge/config'

/* Import mock data */
import { atlanticForces, platformTypes } from '@serge/mocks'
import data from './data/atlantic-cells'
// TODO: here is the 'master' version of the cells,
// in the @serge/data package
// import * as data from '../../../../data/atlantic-cells.json'

const wrapper: React.FC = (storyFn: any) => <div style={{ height: '700px' }}>{storyFn()}</div>

async function fetchMock (): Promise<any> {
  return {
    json: (): any => data
  }
}

export default {
  title: 'local/LocalMapping',
  component: Mapping,
  decorators: [wrapper],
  parameters: {
    readme: {
      // Show readme before story
      content: docs
    },
    options: {
      // We have no addons enabled in this story, so the addon panel should be hidden
      showPanel: true
    },
    controls: {
      expanded: true
    }
  },
  argTypes: {
    playerForce: {
      name: 'View as',
      control: {
        type: 'radio',
        defaultValue: 'Blue',
        options: [
          'White',
          'Blue',
          'Red'
        ]
      }
    },
    phase: {
      name: 'Game phase',
      control: {
        type: 'radio',
        defaultValue: Phase.Planning,
        options: [
          Phase.Planning,
          Phase.Adjudication
        ]
      }
    },
    wargameInitiated: {
      name: 'Wargame has been initiated',
      control: {
        type: 'boolean'
      }
    },
    children: {
      table: {
        disable: true
      }
    }
  }
}

const atlanticConstraints: MappingConstraints = {
  bounds: [[ 50.4, -20], [ 50, -19 ]],
  h3res: 7,
  maxNativeZoom: 7,
  maxZoom: 12,
  minZoom: 5,
  minZoomHexes: 6,
  targetDataset: Domain.ATLANTIC,
  tileDiameterMins: 64, //,
  // "tileLayer": {
  //     "attribution": "Generated by QTiles",
  //     "url": "./atlantic_tiles/{z}/{x}/{y}.png"
  // }
  // gridCellsURL: `${serverPath}cells/atlantic-cells-6k.json`,
  // polygonAreasURL: `${serverPath}cells/atlantic-polygons.json`
}

const localConstraints: MappingConstraints = deepCopy(atlanticConstraints)
localConstraints.tileLayer = {
  url: './atlantic_tiles/{z}/{x}/{y}.png',
  attribution: 'Generated by QTiles'
}

const osmConstraints: MappingConstraints = deepCopy(atlanticConstraints)
osmConstraints.tileLayer = {
  url: 'https://{s}.tile.openstreetmap.de/tiles/osmde/{z}/{x}/{y}.png',
  attribution: 'Data © <a href="http://osm.org/copyright">OpenStreetMap</a>'
}

const detailedConstraints: MappingConstraints = deepCopy(atlanticConstraints)
detailedConstraints.tileLayer = {
  url: './atlantic_tiles/{z}/{x}/{y}.png',
  attribution: 'Generated by QTiles'
}
detailedConstraints.gridCellsURL = `${serverPath}atlantic-detailed.json`
detailedConstraints.tileDiameterMins = 30

interface StoryPropTypes extends MappingPropTypes {
  showAllowableCells?: boolean
  allowableOrigin?: string
  allowableTerrain?: string
  mappingConstraints: MappingConstraints
}

const Template: Story<StoryPropTypes> = (args) => {
  const {
    playerForce,
    ...props
  } = args
  const forceNames = {
    White: 'umpire',
    Blue: 'Blue',
    Red: 'Red'
  }
  return (
    <Mapping
      playerForce={forceNames[playerForce]}
      fetchOverride={fetchMock}
      {...props}
    />
  )
}

const twoFourHours = 1000 * 60 * 60 * 24

/**
 * DEFAULT VIEW
 */
export const NaturalEarth = Template.bind({})
NaturalEarth.args = {
  forces: atlanticForces,
  playerForce: 'Blue',
  gameTurnTime: twoFourHours,
  canSubmitOrders: true,
  platforms: platformTypes,
  phase: Phase.Planning,
  wargameInitiated: true,
  turnNumber: 5,
  mapBar: true,
  mappingConstraints: localConstraints,
  children: (
    <>
      <HexGrid />
      <Assets />
    </>
  )
}

export const OpenStreetMap = Template.bind({})
OpenStreetMap.args = {
  forces: atlanticForces,
  playerForce: 'Blue',
  gameTurnTime: twoFourHours,
  canSubmitOrders: true,
  platforms: platformTypes,
  wargameInitiated: true,
  phase: Phase.Planning,
  turnNumber: 5,
  mapBar: true,
  mappingConstraints: osmConstraints,
  children: (
    <>
      <Assets />
      <HexGrid />
    </>
  )
}

export const DetailedCells = Template.bind({})
DetailedCells.args = {
  forces: atlanticForces,
  playerForce: 'Blue',
  gameTurnTime: twoFourHours,
  canSubmitOrders: true,
  platforms: platformTypes,
  phase: Phase.Planning,
  wargameInitiated: true,
  turnNumber: 5,
  mapBar: true,
  mappingConstraints: detailedConstraints,
  children: (
    <>
      <HexGrid />
      <Assets />
    </>
  )
}
