// import data types
import { Phase } from '@serge/config'
import { ChannelMapping, ChannelTypes, ForceData, MappingConstraints, MessageMap, MilliTurns, Role } from '@serge/custom-types'
import { deepCopy } from '@serge/helpers'
/* Import mock data */
import { watuPlaytest } from '@serge/mocks'
import { Story } from '@storybook/react/types-6-0'
import React from 'react'
import Assets from '../assets'
import { HexGrid } from '../hex-grid'
import InfoMarkers from '../info-markers'
import data from './data/atlantic-cells'
// Import component files
import Mapping from './index'
import docs from './README.md'
import MappingPropTypes from './types/props'

const watuWargame = deepCopy(watuPlaytest)
const forces = deepCopy(watuWargame.data.forces.forces)
const platformTypes = (watuWargame.data.platformTypes && watuWargame.data.platformTypes.platformTypes) || []
const overview = watuWargame.data.overview
const annotations = (watuWargame.data.annotations && watuWargame.data.annotations.annotations) || []
const mapChannel = watuWargame.data.channels.channels.find((channel: ChannelTypes) => channel.name === 'mapping') as ChannelMapping
const icons = (watuWargame.data.annotationIcons && watuWargame.data.annotationIcons.markers) || []
const mapping = mapChannel.constraints

const wrapper: React.FC = (storyFn: any) => <div style={{ height: '700px' }}>{storyFn()}</div>

console.clear()

async function fetchMock (): Promise<any> {
  return {
    json: (): any => data
  }
}

const allRoles: string[] = []
forces.forEach((force: ForceData) => {
  force.roles.forEach((role: Role) => {
    allRoles.push(force.uniqid + ' ~ ' + role.roleId)
  })
})

export default {
  title: 'local/Mapping/Playtest',
  component: Mapping,
  decorators: [wrapper],
  parameters: {
    readme: {
      // Show readme before story
      content: docs
    },
    options: {
      // We have no addons enabled in this story, so the addon panel should be hidden
      showPanel: true
    },
    controls: {
      expanded: true
    }
  },
  argTypes: {
    playerRole: {
      name: 'View as',
      defaultValue: allRoles[0],
      control: {
        type: 'select',
        options: allRoles
      }
    },
    gameTurnTime: {
      name: 'Turn Length',
      defaultValue: (overview.gameTurnTime as MilliTurns).millis,
      control: {
        type: 'radio',
        options: [
          120000, 240000, 300000, 600000
        ]
      }
    },
    phase: {
      name: 'Game phase',
      defaultValue: Phase.Adjudication,
      control: {
        type: 'radio',
        options: [
          Phase.Planning,
          Phase.Adjudication
        ]
      }
    },
    wargameInitiated: {
      name: 'Wargame has been initiated',
      control: {
        type: 'boolean'
      }
    },
    children: {
      table: {
        disable: true
      }
    }
  }
}

const largerMapping = deepCopy(mapping)

const localConstraints: MappingConstraints = deepCopy(largerMapping)
localConstraints.tileLayer = {
  url: './atlantic_tiles/{z}/{x}/{y}.png',
  attribution: 'Generated by QTiles'
}

const mapPostBack = (messageType: string, payload: MessageMap, channelID?: string | number | undefined): void => {
  console.log('index4 postBack', messageType, payload, channelID)
}

interface StoryPropTypes extends MappingPropTypes {
  showAllowableCells?: boolean
  allowableOrigin?: string
  allowableTerrain?: string
  mappingConstraints: MappingConstraints
}

const Template: Story<StoryPropTypes> = (args) => {
  const {
    playerRole,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    playerForce,
    // eslint-disable-next-line @typescript-eslint/no-unused-vars
    isGameControl,
    phase,
    ...props
  } = args
  const roleStr: string = playerRole
  // separate out the two elements of the combined role
  const ind = roleStr.indexOf(' ~ ')
  const force = roleStr.substring(0, ind)
  const role = roleStr.substring(ind + 3)
  const isGameControlRole = roleStr === allRoles[0]
  return (
    <Mapping
      playerForce={force}
      isGameControl={isGameControlRole}
      playerRole={role}
      fetchOverride={fetchMock}
      phase={phase}
      mapPostBack={mapPostBack}
      {...props}
    />
  )
}

const timeStep = (overview.gameTurnTime as MilliTurns).millis

/**
 * DEFAULT VIEW
 */
export const NaturalEarth = Template.bind({})
NaturalEarth.args = {
  forces: forces,
  gameTurnTime: timeStep,
  platforms: platformTypes,
  infoMarkers: annotations,
  markerIcons: icons,
  channel: mapChannel,
  wargameInitiated: true,
  turnNumber: 5,
  mapBar: true,
  mappingConstraints: localConstraints,
  children: (
    <>
      <HexGrid />
      <Assets />
      <InfoMarkers/>
    </>
  )
}
