// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contain-option-menu': string;
  'searchlist-list': string;
  'searchlist-title': string;
  'wargame-option-menu-bg': string;
  'wargame-option-menu-btn': string;
  'wargame-searchlist': string;
}
export const cssExports: CssExports;
export default cssExports;
