// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accordion': string;
  'accordion-header': string;
  'accordion-title': string;
  'add-asset-overlay': string;
  'add-asset-overlay-active': string;
  'add-asset-overlay-dropzone': string;
  'add-asset-overlay-msg': string;
  'arrow-icon': string;
  'asset-name': string;
  'assets-list-box': string;
  'assets-list-scrollable-box': string;
  'attribute-chip': string;
  'attribute-group': string;
  'icon-box': string;
  'icon-box-content': string;
  'icon-box-holder': string;
  'icon-box-name': string;
  'icon-item-main': string;
  'icons-col': string;
  'input-group': string;
  'item-asset-icon-box': string;
  'list-dynamic-input': string;
  'list-input': string;
  'list-item': string;
  'list-item-selected': string;
  'list-title': string;
  'location-select': string;
  'platform-types-box': string;
  'view-result-box': string;
}
export const cssExports: CssExports;
export default cssExports;
