// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'item': string;
  'main': string;
  'progress': string;
  'progress-box': string;
  'progress-indicator': string;
  'progress-indicator-active': string;
  'progress-indicator-complete': string;
  'scale': string;
  'status': string;
}
export const cssExports: CssExports;
export default cssExports;
