// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'input-box': string;
  'item': string;
  'main': string;
  'save-icon': string;
  'status': string;
}
export const cssExports: CssExports;
export default cssExports;
