/* global it expect */
import L from 'leaflet'
import React from 'react'
import { mount } from 'enzyme'

import AssetIcon from './index'
import Mapping from '../mapping'
import { Phase } from '@serge/config'

/* Import mock data */
import { forces, platformTypes } from '@serge/mocks'

const bounds = L.latLngBounds(L.latLng(14.194809302, 42.3558566271), L.latLng(12.401259302, 43.7417816271))

const LocalTileLayer = {
  url: '/tiles/{z}/{x}/{y}.png',
  attribution: 'Generated by QTiles'
}

it('Mapping renders correctly with AssetIcon', () => {
  const div = document.createElement('div')
  document.body.appendChild(div)

  // Using enzyme's 'mount' to solve issues with Leaflet requiring access to the DOM and other features not
  // provided by react.render.
  const tree = mount(<Mapping
    tileDiameterMins = {5}
    bounds = {bounds}
    tileLayer = {LocalTileLayer}
    forces = {forces}
    wargameInitiated = {true}
    platforms = {platformTypes}
    playerForce = 'blue'
    canSubmitOrders = {true}
    phase = {Phase.Planning}
    turnNumber={5}
  ><AssetIcon uniqid='id1' name="Jeffrey" position={L.latLng(13.298034302, 43.0488191271)}
      selected={false} type='agi' force='blue' perceivedForce='blue' visibleTo={['blue']} status={ { speedKts: 10, state: 'Working' }}
      tooltip='Tooltip for marker'/></Mapping>, { attachTo: div })

  expect(tree).toMatchSnapshot()
})
