// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'asset-icon': string;
  'blue': string;
  'force': string;
}
export const cssExports: CssExports;
export default cssExports;
