// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'asset-icon': string;
  'blue': string;
  'force': string;
  'platform-type-agi': string;
  'platform-type-boghammer': string;
  'platform-type-coastal-radar-site': string;
  'platform-type-datum': string;
  'platform-type-destroyer': string;
  'platform-type-fast-attack-craft': string;
  'platform-type-fishing-vessel': string;
  'platform-type-fixed-wing-aircraft': string;
  'platform-type-frigate': string;
  'platform-type-helicopter': string;
  'platform-type-mcmv': string;
  'platform-type-merchant-vessel': string;
  'platform-type-mine': string;
  'platform-type-missile': string;
  'platform-type-pirate': string;
  'platform-type-torpedo': string;
  'platform-type-uas': string;
  'platform-type-unknown': string;
  'popup': string;
  'red': string;
}
export const cssExports: CssExports;
export default cssExports;
