// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'asset-icon': string;
  'button': string;
  'fieldset': string;
  'form-header': string;
  'input-container': string;
  'select': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
