// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'assigned': string;
  'feedback-content': string;
  'feedback-header': string;
  'feedback-icon': string;
  'feedback-item': string;
  'feedback-title': string;
  'inset': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
