// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'wargame-icon': string;
  'wargame-row': string;
  'wargame-started-highlight': string;
  'wargame-title': string;
  'wargame-unstarted-highlight': string;
}
export const cssExports: CssExports;
export default cssExports;
