// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'collapse': string;
  'content': string;
  'content-empty': string;
  'content-group': string;
  'content-group_out': string;
  'dropzone': string;
  'empty-active': string;
  'group-active': string;
  'group_out-active': string;
  'holder': string;
  'item': string;
  'item-hide': string;
  'loading': string;
  'main': string;
  'main-empty': string;
  'main-group_out': string;
  'overlap': string;
  'switch': string;
  'switchitem': string;
}
export const cssExports: CssExports;
export default cssExports;
