// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'collapse': string;
  'dropzone': string;
  'holder': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
