// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contain-force-skin': string;
  'force-skin': string;
  'force-type': string;
  'role-icon': string;
  'role-info': string;
  'role-type': string;
}
export const cssExports: CssExports;
export default cssExports;
