// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'asset-icon-background': string;
  'asset-icon-with-image': string;
  'corner-line': string;
  'img': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
