// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'assets': string;
  'damaged': string;
  'dead': string;
  'full': string;
  'messages-list': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
