// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'add-section': string;
  'button': string;
  'delete-btn': string;
  'drag': string;
  'horizontal': string;
  'horizontallist': string;
  'item': string;
  'li': string;
  'main': string;
  'overlap': string;
  'presection': string;
  'section': string;
  'trash-icon': string;
  'value-label': string;
}
export const cssExports: CssExports;
export default cssExports;
