// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'content': string;
  'header': string;
  'left-panel': string;
  'link': string;
  'loading': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
