// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'private-chat-text-block': string;
  'send-message-icon': string;
  'write-message-panel': string;
}
export const cssExports: CssExports;
export default cssExports;
