// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action-tab': string;
  'active': string;
  'content': string;
  'hide': string;
  'new-order-input': string;
  'order-group': string;
  'panel': string;
  'resize-indicator-container': string;
  'resize-indicator-icon': string;
  'root': string;
  'secondary-action-tab': string;
  'select-template-title': string;
  'tab-panel': string;
  'turn-dropdown': string;
}
export const cssExports: CssExports;
export default cssExports;
