// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'adjudicate': string;
  'fieldset': string;
}
export const cssExports: CssExports;
export default cssExports;
