// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'col': string;
  'color-box': string;
  'form-row': string;
  'role': string;
  'role-item': string;
  'role-title': string;
  'row': string;
  'section': string;
  'states-holder': string;
  'textarea': string;
  'title-center': string;
}
export const cssExports: CssExports;
export default cssExports;
