// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accordion': string;
  'accordion-header': string;
  'accordion-title': string;
  'actions': string;
  'arrow-icon': string;
  'asset-name': string;
  'assets-list-box': string;
  'assets-list-scrollable-box': string;
  'col': string;
  'color-box': string;
  'form-row': string;
  'icon-box': string;
  'icon-box-content': string;
  'icon-box-holder': string;
  'icon-item-main': string;
  'icons-col': string;
  'input-group': string;
  'item-asset-icon': string;
  'item-icon': string;
  'list-item': string;
  'list-item-selected': string;
  'list-title': string;
  'mb_20': string;
  'player-checkbox-label': string;
  'role': string;
  'role-item': string;
  'role-title': string;
  'row': string;
  'section': string;
  'states-holder': string;
  'textarea': string;
  'title-center': string;
  'view-result-box': string;
}
export const cssExports: CssExports;
export default cssExports;
