// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'col': string;
  'color-box': string;
  'mb-20': string;
  'row': string;
  'modal': string;
  'header': string;
  'body': string;
  'footer': string;
}
export const cssExports: CssExports;
export default cssExports;
