// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'adjudication': string;
  'content': string;
  'default': string;
  'form': string;
  'perceived-as': string;
  'planning': string;
  'visibility': string;
}
export const cssExports: CssExports;
export default cssExports;
