// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chat-text-input': string;
  'icon-private': string;
  'private-chat-text-input': string;
}
export const cssExports: CssExports;
export default cssExports;
