Cypress.Commands.add("chooseWarGame", (warName) => {
  cy.wait(500)
  cy.get('.css-1hwfws3.react-select__value-container')
    .click()
  cy.wait(500)
  cy.get('.react-select__option').contains(warName)
    .click()
})
Cypress.Commands.add("chooseRoleGame", (forceName, roleName) => {
  cy.wait(500)
  const locator = 'ul[data-qa-force-name="' + forceName + '"]  button.btn.btn-sm.btn-primary'
  cy.get(locator).contains(roleName)
    .click()
})
Cypress.Commands.add("clickEnterButton", () => {
  cy.wait(500)
  cy.get('button[name="enter-game"]')
    .click()
})
Cypress.Commands.add("clickInitiateButton", () => {
  cy.wait(500)
  cy.get('button[name="initiate-game"]')
    .click()
})
Cypress.Commands.add("chooseRoom", (roomName) => {
  cy.wait(500)
  cy.get('div.flexlayout__tab_button_content').contains(roomName)
  .click()
})
Cypress.Commands.add("sendNewMessage", (turnNumber, overallIntentions, unit, tasking, policy, action, comment) => {
  cy.wait(500)
  cy.get('div[data-channel-id="channel-k2sgtex3"] > .new-message-creator.wrap.new-message-orderable').click()
  cy.wait(500)
  cy.get('input[type="number"]').type(turnNumber)
  cy.get('textarea[name="root[OverallIntentions]"]').type(overallIntentions)
  cy.get('tr[data-schemapath="root.Orders.0"]  input[name="root[Orders][0][Unit]"]').type(unit)
  cy.get('tr[data-schemapath="root.Orders.0"]  name="root[Orders][0][Tasking]"').type(tasking)
  cy.get('tr[data-schemapath="root.Orders.0"]  name="root[Orders][0][SearchPolicy]"').type(policy)
  cy.get('tr[data-schemapath="root.Orders.0"]  name="root[Orders][0][ActionOnContact]"').check(action)
  cy.get('tr[data-schemapath="root.Orders.0"]  name="root[Orders][0][AnyOtherComments]"').type(comment)
  cy.get('button.btn-secondary.json-editor-btntype-add span').contains('Add row').click()
  cy.get('.tab-content-blue-hq > .new-message-creator > .Collapsible > .Collapsible__contentOuter > .Collapsible__contentInner > .form-group > .btn > span').click()
})
