// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'info-badge': string;
  'info-body': string;
  'message-item-unread': string;
  'message-title': string;
  'message-title-opened': string;
  'message-title-wrap': string;
  'marker': string
}
export const cssExports: CssExports;
export default cssExports;
