// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'item': string;
  'main': string;
  'menu': string;
  'overlap': string;
  'section': string;
}
export const cssExports: CssExports;
export default cssExports;
