// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'beat': string;
  'heartbeat-status-icon': string;
  'start': string;
  'stop': string;
}
export const cssExports: CssExports;
export default cssExports;
