// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chat': string;
  'main': string;
  'messages': string;
}
export const cssExports: CssExports;
export default cssExports;
