/***
* This file is autogenerated, please do not edit it.
* To generate an updated version, please run `yarn genreg`
***/

export { default as MessagesMock } from './messages.mock'
export { default as WargameMock } from './wargame.mock'
export { default as forces } from './forces.mock'
export { default as platformTypes } from './platform-types.mock'
export { default as platformType } from './platform-type.mock'
export { default as selectedAsset } from './selected-asset.mock'
export { default as adminTabs } from './admin-tabs.mock'
