/***
* This file is autogenerated, please do not edit it.
* To generate an updated version, please run `yarn genreg`
***/

export { default as MessagesMock } from './messages.mock'
export { default as WargameMock } from './wargame.mock'