import { Wargame } from "@serge/custom-types";

const wargame: Wargame = {
    "adjudicationStartTime": "2021-08-10T16:12:25+01:00",
    "wargameList": [],
    "data": {
        "channels": {
            "channels": [
                {
                    "name": "VHF C16",
                    "channelType": "ChannelCustom",
                    "participants": [
                        {
                            "forceUniqid": "umpire",
                            "roles": [],
                            "subscriptionId": "8qsze9",
                            "templates": [],
                            "pType": "ParticipantCustom"
                        },
                        {
                            "forceUniqid": "Blue-1",
                            "roles": [],
                            "subscriptionId": "hzrzp",
                            "templates": [],
                            "pType": "ParticipantCustom"
                        },
                        {
                            "forceUniqid": "Red-1",
                            "roles": [],
                            "subscriptionId": "icrx",
                            "templates": [],
                            "pType": "ParticipantCustom"
                        }
                    ],
                    "uniqid": "channel-koirdijk"
                },
                {
                    "name": "mapping",
                    "channelType": "mapping",
                    "constraints": {
                        "bounds": [[50.252, -19.55], [50.22, -19.47]],
                        "cellLabelsStyle": "x_y_labels",
                        "gridCellsURL": "cells/atlantic-cells-6k.json",
                        "h3res": 9,
                        "maxZoom": 16,
                        "minZoom": 5,
                        "polygonAreasURL": "cells/atlantic-polygons.json",
                        "tileLayer": {
                            "attribution": "Generated by QTiles",
                            "url": "./atlantic_tiles/{z}/{x}/{y}.png",
                            "maxNativeZoom": 7
                        }
                    },
                    "participants": [
                        {
                            "pType": "ParticipantMapping",
                            "forceUniqid": "umpire",
                            "roles": [],
                            "subscriptionId": "white-view"
                        },
                        {
                            "pType": "ParticipantMapping",
                            "forceUniqid": "umpire",
                            "roles": ["umpire-GC"],
                            "controls": ["control-all:green-force"],
                            "subscriptionId": "white-control-green-all"
                        },
                        {
                            "pType": "ParticipantMapping",
                            "forceUniqid": "umpire",
                            "roles": ["umpire-blue-hq"],
                            "controls": ["merchID2"],
                            "subscriptionId": "white-control-green-asset"
                        },
                        {
                            "forceUniqid": "Blue-1",
                            "roles": [],
                            "subscriptionId": "w9lmf",
                            "pType": "ParticipantMapping"
                        },
                        {
                            "forceUniqid": "Blue-1",
                            "roles": ["nortCO"],
                            "subscriptionId": "nortCO-control",
                            "pType": "ParticipantMapping",
                            "controls": ["nortID"]
                        },
                        {
                            "forceUniqid": "Blue-1",
                            "roles": ["blueCO"],
                            "subscriptionId": "blue-CO-control-all",
                            "pType": "ParticipantMapping",
                            "controls": ["control-all:Blue-1"]
                        },
                        {
                            "forceUniqid": "Red-1",
                            "roles": ["red-CO"],
                            "subscriptionId": "red-co-all",
                            "controls": ["control-all:Red-1"],
                            "pType": "ParticipantMapping"
                        },
                        {
                            "forceUniqid": "Red-1",
                            "roles": [],
                            "subscriptionId": "red-viewers",
                            "pType": "ParticipantMapping"
                        }
                    ],
                    "uniqid": "channel-koirldxk"
                }
            ],
            "dirty": false,
            "name": "Channels",
            "selectedChannel": ""
        },
        "forces": {
            "dirty": false,
            "forces": [
                {
                    "color": "#FCFBEE",
                    "dirty": false,
                    "iconURL": "http://localhost:8080/default_img/umpireDefault.png",
                    "name": "White Force",
                    "overview": "Umpire force.",
                    "roles": [
                        {
                            "isGameControl": true,
                            "isInsightViewer": true,
                            "isObserver": true,
                            "isRFIManager": false,
                            "name": "Game Control",
                            "roleId": "umpire-GC"
                        },
                        {
                            "isGameControl": false,
                            "isInsightViewer": true,
                            "isObserver": false,
                            "isRFIManager": true,
                            "name": "RFI Mgr",
                            "roleId": "rks5zfzd3"
                        },
                        {
                            "isGameControl": false,
                            "isInsightViewer": false,
                            "isObserver": false,
                            "isRFIManager": false,
                            "name": "Blue HHQ",
                            "roleId": "umpire-blue-hq"
                        },
                        {
                            "isGameControl": false,
                            "isInsightViewer": false,
                            "isObserver": false,
                            "isRFIManager": false,
                            "name": "Red HHQ",
                            "roleId": "rks5zfzd5"
                        }
                    ],
                    "umpire": true,
                    "uniqid": "umpire"
                },
                {
                    "assets": [
                        {
                            "condition": "Working",
                            "contactId": "C426",
                            "history": [
                                {
                                    "route": [
                                        "8918aab725bffff"
                                    ],
                                    "status": {
                                        "speedKts": 12,
                                        "state": "Transiting a"
                                    },
                                    "turn": 1
                                }, {
                                    "status": {
                                        "state": "Moored"
                                    },
                                    "turn": 2
                                }, {
                                    "route": [
                                        "8918aab7203ffff"
                                    ],
                                    "status": {
                                        "speedKts": 12,
                                        "state": "Transiting b"
                                    },
                                    "turn": 2
                                }
                            ],
                            "hosting": [
                                {
                                    "condition": "Full capability",
                                    "contactId": "C572",
                                    "history": [],
                                    "name": "Merlin",
                                    "perceptions": [
                                        {
                                            "by": "Red-1",
                                            "force": "Blue-1",
                                            "typeId": "a8"
                                        }
                                    ],
                                    "plannedTurns": [],
                                    "platformTypeId": "a8",
                                    "status": {
                                        "state": "Landed"
                                    },
                                    "uniqid": "nort-merlin"
                                },
                                {
                                    "condition": "Full capability",
                                    "contactId": "C591",
                                    "history": [],
                                    "name": "Dart 42",
                                    "perceptions": [],
                                    "plannedTurns": [],
                                    "platformTypeId": "a10",
                                    "status": {
                                        "state": "Landed"
                                    },
                                    "uniqid": "nort-dart"
                                }
                            ],
                            "name": "NORT",
                            "perceptions": [
                                {
                                    "by": "Red-1",
                                    "force": "Blue-1",
                                    "typeId": "a4"
                                }
                            ],
                            "plannedTurns": [
                                {
                                    "route": [
                                        "8918a84db3bffff"
                                    ],
                                    "status": {
                                        "speedKts": 20,
                                        "state": "Transiting"
                                    },
                                    "turn": 1
                                },
                                {
                                    "status": {
                                        "state": "Moored"
                                    },
                                    "turn": 2
                                }

                            ],
                            "platformTypeId": "a6",
                            "attributeValues": [
                                {
                                    "attrId": "asdic-dir",
                                    "attrType": "AttributeValueNumber",
                                    "value": 150
                                },
                                {
                                    "attrId": "att-torpedoes",
                                    "value": 25,
                                    "attrType": "AttributeValueNumber"
                                }
                            ],
                            "position": "8918aab7003ffff",
                            "uniqid": "nortID"
                        },
                        {
                            "condition": "Working",
                            "contactId": "C164",
                            "history": [{
                                "route": [
                                    "8918aab604bffff"
                                ],
                                "status": {
                                    "speedKts": 6,
                                    "state": "Transiting"
                                },
                                "turn": 1
                            }, {
                                "status": {
                                    "state": "Moored"
                                },
                                "turn": 2
                            }, {
                                "route": [
                                    "8918aab6283ffff"
                                ],
                                "status": {
                                    "speedKts": 12,
                                    "state": "Transiting"
                                },
                                "turn": 3
                            }],
                            "name": "TALN",
                            "attributeValues": [
                                {
                                    "attrId": "comm-battery",
                                    "value": 100,
                                    "attrType": "AttributeValueNumber"
                                }
                            ],
                            "perceptions": [
                                {
                                    "by": "Red-1",
                                    "force": "Blue-1",
                                    "name": "Blue Warship",
                                    "typeId": "a3"
                                },
                                {
                                    "by": "Red-2",
                                    "force": "Blue-1",
                                    "typeId": "a4"
                                }
                            ],
                            "platformTypeId": "a8",
                            "position": "8918aab7547ffff",
                            "uniqid": "talnID"
                        },
                        {
                            "condition": "Working",
                            "contactId": "C866",
                            "history": [
                                {
                                    "route": [
                                        "8918aab648bffff"
                                    ],
                                    "status": {
                                        "speedKts": 12,
                                        "state": "Transiting a"
                                    },
                                    "turn": 1
                                },
                                {
                                    "route": [
                                        "8918aab6447ffff"
                                    ],
                                    "status": {
                                        "speedKts": 10,
                                        "state": "Transiting b"
                                    },
                                    "turn": 2
                                }
                            ],
                            "name": "SSN-2",
                            "perceptions": [],
                            "platformTypeId": "a8",
                            "position": "8918aab66bbffff",
                            "uniqid": "a0a975y4221"
                        }, {
                            "condition": "Full capability",
                            "contactId": "C713",
                            "history": [
                                {
                                    "route": [
                                        "8918aab0c2fffff"
                                    ],
                                    "status": {
                                        "speedKts": 10,
                                        "state": "Transiting"
                                    },
                                    "turn": 0
                                },
                                {
                                    "route": [
                                        "8918aab08b3ffff"
                                    ],
                                    "status": {
                                        "speedKts": 20,
                                        "state": "Transiting"
                                    },
                                    "turn": 1
                                },
                                {
                                    "route": [
                                        "8918aab0d63ffff"
                                    ],
                                    "status": {
                                        "speedKts": 30,
                                        "state": "Transiting"
                                    },
                                    "turn": 2
                                }
                            ],
                            "comprising": [
                                {
                                    "condition": "Full capability",
                                    "contactId": "C964",
                                    "history": [],
                                    "name": "Frigate A",
                                    "perceptions": [
                                        {
                                            "by": "Red-1",
                                            "force": "Blue-1",
                                            "name": "Frigate A Perceived Name",
                                            "typeId": "a3"
                                        }
                                    ],
                                    "platformTypeId": "a3",
                                    "hosting": [
                                        {
                                            "condition": "Full capability",
                                            "contactId": "C721",
                                            "history": [],
                                            "name": "Dart 45",
                                            "perceptions": [
                                                {
                                                    "by": "Red-1",
                                                    "force": "Blue-1",
                                                    "name": "Unknown UAV",
                                                    "typeId": "a10"
                                                }
                                            ],
                                            "plannedTurns": [],
                                            "platformTypeId": "a10",
                                            "status": {
                                                "state": "Landed"
                                            },
                                            "uniqid": "tg-frig-uav1"
                                        },
                                        {
                                            "condition": "Full capability",
                                            "contactId": "C932",
                                            "history": [],
                                            "name": "Dart 46",
                                            "perceptions": [],
                                            "plannedTurns": [],
                                            "platformTypeId": "a10",
                                            "status": {
                                                "state": "Landed"
                                            },
                                            "uniqid": "a0pra17943"
                                        }
                                    ],
                                    "status": {
                                        "speedKts": 20,
                                        "state": "Transiting"
                                    },
                                    "uniqid": "tg-frigate"
                                },
                                {
                                    "condition": "Full capability",
                                    "contactId": "C653",
                                    "history": [],
                                    "name": "MCM Delta",
                                    "perceptions": [
                                        { "by": "Red-1", "force": "Blue-1", "name": "Blue MCM", "typeId": "a9" }
                                    ],
                                    "platformTypeId": "a9",
                                    "status": {
                                        "speedKts": 20,
                                        "state": "Transiting"
                                    },
                                    "uniqid": "tg-mcm"
                                }
                            ],
                            "name": "CTF 511",
                            "perceptions": [
                                {
                                    "by": "Red",
                                    "force": "Blue-1",
                                    "name": "BRIT",
                                    "typeId": "a11"
                                }
                            ],
                            "plannedTurns": [
                                {
                                    "route": [
                                        "8918aab0dafffff",
                                        "8918aab0db7ffff"
                                    ],
                                    "status": {
                                        "speedKts": 20,
                                        "state": "Transiting"
                                    },
                                    "turn": 4
                                },
                                {
                                    "route": [
                                        "8918aab766fffff"
                                    ],
                                    "status": {
                                        "speedKts": 20,
                                        "state": "Transiting"
                                    },
                                    "turn": 5
                                }
                            ],
                            "platformTypeId": "a16",
                            "position": "8918aab0d07ffff",
                            "status": {
                                "speedKts": 20,
                                "state": "Transiting"
                            },
                            "uniqid": "a0pra5431"
                        }
                    ],
                    "color": "#00aaff",
                    "cssClass": "blue-1",
                    "dirty": false,
                    "iconURL": "http://localhost:8080/default_img/forceDefault.png",
                    "name": "Blue-1 Force",
                    "overview": "An overview written here..",
                    "roles": [
                        {
                            "isGameControl": false,
                            "isInsightViewer": false,
                            "isObserver": false,
                            "name": "CO",
                            "roleId": "blueCO"
                        },
                        {
                            "isGameControl": false,
                            "isInsightViewer": false,
                            "isObserver": false,
                            "isRFIManager": false,
                            "name": "NORT CO",
                            "roleId": "nortCO"
                        },
                        {
                            "isGameControl": false,
                            "isInsightViewer": false,
                            "isObserver": false,
                            "isRFIManager": false,
                            "name": "Comms",
                            "roleId": "blue-comms"
                        }

                    ],
                    "umpire": false,
                    "uniqid": "Blue-1",
                    "visibleTo": []
                },
                {
                    "assets": [
                        {
                            "condition": "Working",
                            "contactId": "C122",
                            "history": [{
                                "status": {
                                    "state": "Moored 1"
                                },
                                "turn": 1
                            },
                            {
                                "status": {
                                    "state": "Scanning 1"
                                },
                                "turn": 2
                            }],
                            "name": "AGI",
                            "perceptions": [
                                {
                                    "by": "Blue-1",
                                    "force": "Red-1"
                                },
                                {
                                    "by": "Blue-2",
                                    "force": "Red-1"
                                }
                            ],
                            "plannedTurns": [
                                {
                                    "route": [
                                        "8918a84db47ffff"
                                    ],
                                    "status": {
                                        "speedKts": 12,
                                        "state": "Transiting a"
                                    },
                                    "turn": 3
                                }, {
                                    "status": {
                                        "state": "Moored"
                                    },
                                    "turn": 4
                                }],
                            "platformTypeId": "a15",
                            "position": "8918a84db3bffff",
                            "uniqid": "red-AGI"
                        },
                        {
                            "condition": "Working",
                            "contactId": "C442",
                            "history": [{
                                "status": {
                                    "state": "Landed"
                                },
                                "turn": 1
                            }, {
                                "status": {
                                    "state": "Refueling"
                                },
                                "turn": 2
                            }],
                            "name": "MPA 2",
                            "perceptions": [
                                {
                                    "by": "Blue-1",
                                    "force": "Red-1",
                                    "typeId": "a12"
                                },
                                {
                                    "by": "Blue-2",
                                    "force": "Red-1"
                                }
                            ],
                            "plannedTurns": [
                                {
                                    "status": {
                                        "state": "Landed"
                                    },
                                    "turn": 2
                                }

                            ], "platformTypeId": "a11",
                            "position": "8918a84db33ffff",
                            "uniqid": "red-mpa-2"
                        }
                    ],
                    "color": "#f00",
                    "cssClass": "red-1",
                    "dirty": false,
                    "iconURL": "http://localhost:8080/default_img/forceDefault.png",
                    "name": "Red-1 Force",
                    "overview": "An overview written here..",
                    "roles": [
                        {
                            "isGameControl": false,
                            "isInsightViewer": false,
                            "isObserver": false,
                            "name": "CO",
                            "roleId": "red-CO"
                        },
                        {
                            "isGameControl": false,
                            "isInsightViewer": false,
                            "isObserver": false,
                            "isRFIManager": false,
                            "name": "CTF Y1",
                            "roleId": "rks5zfzdj"
                        },
                        {
                            "isGameControl": false,
                            "isInsightViewer": false,
                            "isObserver": false,
                            "isRFIManager": false,
                            "name": "CTF Y2",
                            "roleId": "rks5zfzdk"
                        },
                        {
                            "isGameControl": false,
                            "isInsightViewer": false,
                            "isObserver": false,
                            "isRFIManager": false,
                            "name": "CTF Y3",
                            "roleId": "rks5zfzdl"
                        },
                        {
                            "isGameControl": false,
                            "isInsightViewer": false,
                            "isObserver": false,
                            "isRFIManager": false,
                            "name": "CTF Y4",
                            "roleId": "rks5zfzdm"
                        },
                        {
                            "isGameControl": false,
                            "isInsightViewer": false,
                            "isObserver": false,
                            "isRFIManager": false,
                            "name": "CTF Y5",
                            "roleId": "rks5zfzdn"
                        }
                    ],
                    "umpire": false,
                    "uniqid": "Red-1",
                    "visibleTo": []
                },
                {
                    "color": "#0d0",
                    "assets": [
                        {
                            "condition": "Working",
                            "contactId": "C526",
                            "history": [],
                            "name": "MERCH 1",
                            "perceptions": [],
                            "plannedTurns": [],
                            "platformTypeId": "a13",
                            "attributeValues": [],
                            "position": "8918a84d94fffff",
                            "uniqid": "merchID"
                        },
                        {
                            "condition": "Working",
                            "contactId": "C926",
                            "history": [],
                            "name": "MERCH 2",
                            "perceptions": [],
                            "plannedTurns": [],
                            "platformTypeId": "a13",
                            "attributeValues": [],
                            "position": "8918aab6623ffff",
                            "uniqid": "merchID2"
                        }
                    ],
                    "dirty": false,
                    "iconURL": "http://localhost:8080/default_img/umpireDefault.png",
                    "name": "Green Force",
                    "overview": "Green force.",
                    "roles": [],
                    "umpire": false,
                    "uniqid": "green-force"
                }
            ],
            "name": "Forces",
            "selectedForce": ""
        },
        "overview": {
            "dirty": false,
            "gameDate": "2021-05-13T16:12",
            "gameDescription": "",
            "gameTurnTime": {
                "millis": 240000,
                "unit": "millis"
            },
            "name": "Overview - settings",
            "realtimeTurnTime": 300000,
            "showAccessCodes": true,
            "timeWarning": 60000,
            "logPlayerActivity": true,
            "turnPresentation": "Natural"
        },
        "platformTypes": {
            "dirty": false,
            "name": "Platform Types",
            "platformTypes": [
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "frigate.svg",
                    "name": "frigate",
                    "speedKts": [
                        6,
                        12,
                        18,
                        24
                    ],
                    "states": [
                        {
                            "mobile": true,
                            "name": "Transiting"
                        },
                        {
                            "mobile": true,
                            "name": "Mixed"
                        },
                        {
                            "mobile": true,
                            "name": "Active"
                        },
                        {
                            "mobile": true,
                            "name": "Passive"
                        }
                    ],
                    "travelMode": "sea",
                    "uniqid": "a1"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "frigate-ta.svg",
                    "name": "frigate-ta",
                    "speedKts": [
                        6,
                        12,
                        18,
                        24
                    ],
                    "states": [
                        {
                            "mobile": true,
                            "name": "Transiting"
                        },
                        {
                            "mobile": true,
                            "name": "Mixed"
                        },
                        {
                            "mobile": true,
                            "name": "Active"
                        },
                        {
                            "mobile": true,
                            "name": "Passive"
                        }
                    ],
                    "travelMode": "sea",
                    "uniqid": "a2"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "missile.svg",
                    "name": "Missile",
                    "states": [
                        {
                            "mobile": false,
                            "name": "Inactive"
                        },
                        {
                            "mobile": true,
                            "name": "Deployed"
                        }
                    ],
                    "travelMode": "air",
                    "uniqid": "a3"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "carrier.svg",
                    "name": "Carrier",
                    "speedKts": [
                        6,
                        12,
                        18,
                        24,
                        30
                    ],
                    "states": [
                        {
                            "mobile": true,
                            "name": "Transiting"
                        },
                        {
                            "mobile": true,
                            "name": "Air Ops"
                        }
                    ],
                    "travelMode": "sea",
                    "uniqid": "a4"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "auxiliary.svg",
                    "name": "Auxiliary",
                    "speedKts": [
                        6,
                        12
                    ],
                    "states": [
                        {
                            "mobile": true,
                            "name": "Transiting"
                        },
                        {
                            "mobile": true,
                            "name": "Supporting"
                        }
                    ],
                    "travelMode": "sea",
                    "uniqid": "a5"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "destroyer.svg",
                    "orientation": [{
                        "attribute": "asdic-dir",
                        "origin": "absolute"
                    }, {}],
                    "name": "Destroyer",
                    "speedKts": [
                        6,
                        12,
                        18,
                        24,
                        30,
                        36
                    ],
                    "states": [
                        {
                            "mobile": true,
                            "name": "Transiting"
                        },
                        {
                            "mobile": false,
                            "name": "Loitering"
                        }
                    ],
                    "turningCircle": 500,
                    "attributeTypes": [
                        {
                            "name": "ASDIC",
                            "attrId": "asdic-dir",
                            "description": "ASDIC orientation (absolute)",
                            "defaultValue": 0,
                            "editableByPlayer": true,
                            "attrType": "AttributeTypeNumber"
                        },
                        {
                            "name": "Torpedoes",
                            "attrId": "att-torpedoes",
                            "description": "Number of torpedoes remaining",
                            "defaultValue": 20,
                            "editableByPlayer": false,
                            "attrType": "AttributeTypeNumber"
                        }
                    ],
                    "travelMode": "sea",
                    "uniqid": "a6"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "ssk.svg",
                    "attributeTypes": [
                        {
                            "name": "Depth",
                            "attrId": "ssk-depth",
                            "description": "Depth",
                            "defaultValue": 'Deep',
                            "values": ["Deep", "PD", "Shallow"],
                            "editableByPlayer": true,
                            "attrType": "AttributeTypeEnum"
                        }
                    ],
                    "name": "SSK",
                    "speedKts": [
                        6,
                        12,
                        18
                    ],
                    "states": [
                        {
                            "mobile": true,
                            "name": "Transiting"
                        },
                        {
                            "mobile": true,
                            "name": "Aggressove"
                        },
                        {
                            "mobile": true,
                            "name": "Evasive"
                        }
                    ],
                    "travelMode": "sea",
                    "uniqid": "a7"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "ssn.svg",
                    "name": "SSN",
                    "orientation": [{
                    }],
                    "attributeTypes": [
                        {
                            "name": "Battery Level",
                            "units": "%",
                            "description": "Charge remaining",
                            "attrId": "comm-battery",
                            "defaultValue": 100,
                            "editableByPlayer": false,
                            "attrType": "AttributeTypeNumber"
                        }
                    ],
                    "speedKts": [
                        6,
                        12,
                        18,
                        24
                    ],
                    "states": [
                        {
                            "mobile": true,
                            "name": "Transiting"
                        },
                        {
                            "mobile": true,
                            "name": "Aggressove"
                        },
                        {
                            "mobile": true,
                            "name": "Evasive"
                        }
                    ],
                    "travelMode": "sea",
                    "uniqid": "a8"
                },
                {
                    "conditions": [
                        "Clearing",
                        "Transiting",
                        "Inactive"
                    ],
                    "icon": "mcmv.svg",
                    "name": "MCMV",
                    "states": [
                        {
                            "mobile": true,
                            "name": "Active"
                        }
                    ],
                    "travelMode": "sea",
                    "uniqid": "a9"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "helicopter.svg",
                    "name": "Helicopter",
                    "states": [
                        {
                            "mobile": true,
                            "name": "Active"
                        },
                        {
                            "mobile": false,
                            "name": "Landed"
                        }
                    ],
                    "travelMode": "air",
                    "uniqid": "a10"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "mpa.svg",
                    "name": "mpa",
                    "states": [
                        {
                            "mobile": true,
                            "name": "Active"
                        },
                        {
                            "mobile": false,
                            "name": "Landed"
                        }
                    ],
                    "travelMode": "air",
                    "uniqid": "a11"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "fixed-wing-aircraft.svg",
                    "name": "Fixed Wing Aircraft",
                    "states": [
                        {
                            "mobile": true,
                            "name": "Active"
                        },
                        {
                            "mobile": false,
                            "name": "Landed"
                        }
                    ],
                    "travelMode": "air",
                    "uniqid": "a12"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "merchant-vessel.svg",
                    "name": "Merchant vessel",
                    "speedKts": [
                        6,
                        12
                    ],
                    "states": [
                        {
                            "mobile": true,
                            "name": "Transiting"
                        },
                        {
                            "mobile": false,
                            "name": "Moored"
                        }
                    ],
                    "travelMode": "sea",
                    "turningCircle": 310,
                    "uniqid": "a13"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "boghammer.svg",
                    "name": "Boghammer",
                    "speedKts": [
                        6,
                        12,
                        18,
                        24,
                        30
                    ],
                    "states": [
                        {
                            "mobile": true,
                            "name": "Transiting"
                        },
                        {
                            "mobile": false,
                            "name": "Moored"
                        }
                    ],
                    "travelMode": "sea",
                    "uniqid": "a14"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "agi.svg",
                    "name": "AGI",
                    "speedKts": [
                        6,
                        12,
                        18
                    ],
                    "states": [
                        {
                            "mobile": true,
                            "name": "Transiting"
                        },
                        {
                            "mobile": false,
                            "name": "Moored"
                        }
                    ],
                    "travelMode": "sea",
                    "uniqid": "a15"
                },
                {
                    "conditions": [
                        "Working",
                        "Disabled",
                        "Mission Kill"
                    ],
                    "icon": "task-group.svg",
                    "name": "Task Group",
                    "speedKts": [
                        6,
                        12,
                        18,
                        24,
                        30
                    ],
                    "states": [
                        {
                            "mobile": true,
                            "name": "Transiting"
                        },
                        {
                            "mobile": false,
                            "name": "Stopped"
                        },
                        {
                            "mobile": false,
                            "name": "Moored"
                        }
                    ],
                    "travelMode": "sea",
                    "uniqid": "a16"
                }
            ],
            "selectedType": ""
        },
        "annotations": {
            "annotations": [{
                "uniqid": "marker-one",
                "color": "#f00",
                "description": "description for the annotation",
                "iconId": "unk",
                "label": "first marker",
                "shadeRadius": 2,
                "location": "8918aab76abffff",
                "visibleTo": ["Blue-1"]
            }, {
                "uniqid": "marker-two",
                "color": "#099",
                "description": "description for the second annotation",
                "iconId": "gen",
                "shadeRadius": 5,
                "label": "second marker",
                "location": "8918a84db3bffff",
                "visibleTo": ["Blue-1", "Red-1"]
            }, {
                "uniqid": "marker-three",
                "color": "#909",
                "description": "description for the third annotation",
                "iconId": "aud",
                "shadeRadius": 0,
                "label": "third marker",
                "location": "8918aab2b0bffff",
                "visibleTo": ["Red-1"]
            }]
        },
        "annotationIcons": {
            "markers": [{ "uniqid": "unk", "name": "Unknown", "icon": "marker_unknown.svg" },
            { "uniqid": "a/v", "name": "Audio-Visual", "icon": "marker_audio_visual.svg" },
            { "uniqid": "aud", "name": "Audio", "icon": "marker_audio.svg" },
            { "uniqid": "flsh", "name": "Flash", "icon": "marker_flash.svg" },
            { "uniqid": "gen", "name": "General", "icon": "marker_general.svg" },
            { "uniqid": "peri", "name": "Periscope", "icon": "marker_periscope.svg" },
            { "uniqid": "plum", "name": "Plume", "icon": "marker_plume.svg" },
            { "uniqid": "wak", "name": "Wake", "icon": "marker_wake.svg" },
            { "uniqid": "vis", "name": "Visual", "icon": "marker_visual.svg" }
            ]
        },
        "templates": {
            "templates": [
                {
                  "completed": false,
                  "details": {
                    "properties": {
                      "Reference": {
                        "title": 'Reference',
                        "type": 'string',
                        "format": 'text'
                      },
                      "Title": {
                        "title": 'Title',
                        "type": 'string',
                        "format": 'text'
                      },
                      "Forces": {
                        "format": 'table',
                        "items": {
                          "minItems": 1,
                          "properties": {
                            "assets": {
                              "format": 'table',
                              "items": {
                                "properties": {
                                  "location": {
                                    "maxLength": 3,
                                    "type": 'string'
                                  },
                                  "name": {
                                    "type": 'string'
                                  },
                                  "visibleTo": {
                                    "format": 'table',
                                    "items": {
                                      "properties": {
                                        "Force": {
                                          'enum': [
                                            'Blue',
                                            'Red',
                                            'Green'
                                          ],
                                          "type": 'string'
                                        }
                                      }
                                    },
                                    "type": 'array'
                                  }
                                }
                              },
                              "minItems": 1,
                              "type": 'array'
                            },
                            'force': {
                              'enum': [
                                'Blue',
                                'Red',
                                'Green'
                              ],
                              "propertyOrder": 100,
                              'type': 'string'
                            }
                          }
                        },
                        'minItems': 1,
                        'type': 'array'
                      }
                    },
                    "title": 'State of World (laydown 2)',
                    "type": 'object'
                  },
                  "lastUpdated": '2019-09-30T12:37:26.705Z',
                  "title": 'State of World L',
                  "_id": 'k16eedkp',
                  "_rev": '1-612d7dc5d10fc81bc7459b2801c66816'
                },
                {
                  "lastUpdated": '2019-09-30T12:37:26.705Z',
                  "title": 'Daily intentions',
                  "details": {
                    "type": 'object',
                    "properties": {
                      "TurnNumber": {
                        "title": 'Turn',
                        "type": 'string',
                        "format": 'number'
                      },
                      "OverallIntentions": {
                        "title": 'Overall intentions',
                        "type": 'string',
                        "format": 'textarea'
                      },
                      "Orders": {
                        "items": {
                          "properties": {
                            "Unit": {
                              "title": 'Unit',
                              "type": 'string',
                              "format": 'text'
                            },
                            "Tasking": {
                              "title": 'Tasking',
                              "type": 'string',
                              "format": 'textarea'
                            },
                            "SearchPolicy": {
                              "title": 'Search Policy',
                              "type": 'string',
                              "format": 'textarea'
                            },
                            "ActionOnContact": {
                              "title": 'Action on Contact',
                              "type": 'string',
                              'enum': [
                                'Ignore',
                                'Evade',
                                'Covert Trail',
                                'Overt Trail',
                                'Harass'
                              ]
                            },
                            "AnyOtherComments": {
                              "title": 'Any other comments',
                              "type": 'string',
                              "format": 'textarea'
                            }
                          },
                          "type": 'object'
                        },
                        "title": 'Orders',
                        "type": 'array',
                        "format": 'table',
                        "minItems": 1
                      }
                    },
                    "title": 'Daily Intent',
                    "required": [
                      'OverallIntentions',
                      'Orders'
                    ]
                  },
                  "completed": false,
                  "_id": 'k16eedkn',
                  "_rev": '1-cc8e8cdb01447959c266761066448382'
                },
                {
                  "lastUpdated": '2019-09-30T12:37:26.705Z',
                  "title": 'Link',
                  "details": {
                    "type": 'object',
                    "properties": {
                      "Title": {
                        "type": 'string',
                        "format": 'text'
                      },
                      "URL": {
                        "type": 'string',
                        "format": 'url'
                      }
                    },
                    "title": 'Link',
                    "format": 'grid'
                  },
                  "completed": false,
                  "_id": 'k16eedkm',
                  "_rev": '1-7fa1e6dd6b4ac5b6afc45b596ee7af61'
                },
                {
                  "lastUpdated": '2019-09-30T12:37:26.705Z',
                  "title": 'Chat',
                  "details": {
                    "type": 'object',
                    "properties": {
                      "content": {
                        "type": 'string',
                        "format": 'textarea',
                        "options": {
                          "inputAttributes": {
                            "placeholder": 'type the text'
                          }
                        }
                      }
                    },
                    "title": 'Chat',
                    "format": 'grid'
                  },
                  "completed": false,
                  "_id": 'k16eedkl',
                  "_rev": '1-09ab7a18ff677cec5d9a56f02a45788d'
                },
                {
                  "completed": false,
                  "details": {
                    "title": "COA",
                    "type": "object",
                    "format": "grid",
                    "required": [
                      "Reference",
                      "Title",
                      "LOCATION",
                      "PRESCRIPTED",
                      "VISIBILITY",
                      "COA_SUPPORTS_AS",
                      "TARGET",
                      "STRAT_COMMS",
                      "OBJECTIVES_TURN",
                      "OBJECTIVES_OVERALL",
                      "TARGET_CENTRE_OF_GRAVITY",
                      "DESIRED_ENDSTATE_TURN",
                      "DESIRED_ENDSTATE_OVERALL",
                      "EFFECTS_AND_ACTIONS",
                      "SEQUENCING_AND_PHASES",
                      "ADVERSARY_UNDERSTANDING",
                      "ADVERSARY_REACTION_COUNTER_ACTION",
                      "ORBAT",
                      "TIMINGS",
                      "DEPENDENCIES",
                      "AdjudicationSupport",
                      "PEER_REVIEW",
                      "INSIGHT"
                    ],
                    "properties": {
                      "Reference": {
                        "type": "string",
                        "title": "Reference (sys generated)",
                        "readonly": "readonly"
                      },
                      "Title": {
                        "type": "string",
                        "title": "*COA / Op Name",
                        "format": "textarea"
                      },
                      "LOCATION": {
                        "title": "*Location of activities in this turn",
                        "type": "object",
                        "properties": {
                          "region": {
                            "title": "Region",
                            "type": "string",
                            "enum": [
                              "Asia Pacific",
                              "Europe",
                              "Americas"
                            ],
                            "default": "Europe"
                          },
                          "Europe": {
                            "title": "Country",
                            "type": "string",
                            "enum": [
                              "United Kingdom",
                              "Germany"
                            ],
                            "options": {
                              "dependencies": {
                                "region": "Europe"
                              }
                            }
                          },
                          "Americas": {
                            "title": "Country",
                            "type": "string",
                            "enum": [
                              "United State of America",
                              "Brazil"
                            ],
                            "options": {
                              "dependencies": {
                                "region": "Americas"
                              }
                            }
                          },
                          "AsiaPacific": {
                            "title": "Country",
                            "type": "string",
                            "enum": [
                              "India",
                              "China"
                            ],
                            "options": {
                              "dependencies": {
                                "region": "Asia Pacific"
                              }
                            }
                          }
                        }
                      },
                      "PRESCRIPTED": {
                        "type": "boolean",
                        "format": "checkbox",
                        "title": "*Is this a pre-scripted activity? E.g. DXP",
                        "default": "Yes",
                        "items": {
                          "type": "string",
                          "enum": [
                            "Yes",
                            "No"
                          ]
                        }
                      },
                      "VISIBILITY": {
                        "type": "string",
                        "title": "*Intended visibility to adversary",
                        "enum": [
                          "Overt",
                          "Covert",
                          "Clandestine",
                          "Complex"
                        ]
                      },
                      "COA_SUPPORTS_AS": {
                        "type": "boolean",
                        "format": "checkbox",
                        "title": "*This COA supports / uses an AS plan / effect",
                        "default": "Yes",
                        "items": {
                          "type": "string",
                          "enum": [
                            "Yes",
                            "No"
                          ]
                        }
                      },
                      "TARGET": {
                        "type": "string",
                        "title": "*Target(s) – Adversary, Ally, specific audience within Adversary or allied polity etc",
                        "format": "textarea",
                        "notEmpty": true
                      },
                      "STRAT_COMMS": {
                        "type": "string",
                        "title": "Outline of associated Strategic Communications",
                        "format": "textarea"
                      },
                      "OBJECTIVES_TURN": {
                        "type": "string",
                        "title": "Objectives in this turn",
                        "format": "textarea"
                      },
                      "OBJECTIVES_OVERALL": {
                        "type": "string",
                        "title": "Overall Objectives",
                        "format": "textarea"
                      },
                      "TARGET_CENTRE_OF_GRAVITY": {
                        "type": "string",
                        "title": "Target’s Centre of Gravity",
                        "format": "textarea"
                      },
                      "DESIRED_ENDSTATE_TURN": {
                        "type": "string",
                        "title": "*Desired Endstate in this turn",
                        "format": "textarea"
                      },
                      "DESIRED_ENDSTATE_OVERALL": {
                        "type": "string",
                        "title": "Desired Endstate Overall, if NOT in this turn",
                        "format": "textarea"
                      },
                      "EFFECTS_AND_ACTIONS": {
                        "type": "string",
                        "title": "*Effects and actions",
                        "format": "textarea"
                      },
                      "SEQUENCING_AND_PHASES": {
                        "type": "string",
                        "title": "Sequencing and phases",
                        "format": "textarea"
                      },
                      "ADVERSARY_UNDERSTANDING": {
                        "type": "string",
                        "title": "What would my adversary see / understand of this activity / messaging?",
                        "format": "textarea"
                      },
                      "ADVERSARY_REACTION_COUNTER_ACTION": {
                        "properties": {
                          "ADVERSARY_MLCOA": {
                            "title": "Adversary MLCOA",
                            "type": "string",
                            "format": "textarea"
                          },
                          "MLCOA_RESPONSE": {
                            "title": "Own Response",
                            "type": "string",
                            "format": "textarea"
                          },
                          "ADVERSARY_MDCOA": {
                            "title": "Adversary MDCOA",
                            "type": "string",
                            "format": "textarea"
                          },
                          "MDCOA_RESPONSE": {
                            "title": "Own Response",
                            "type": "string",
                            'format': "textarea"
                          }
                        },
                        "title": "Adversary reaction & counter-action",
                        "type": "object"
                      },
                      "ORBAT": {
                        "type": "array",
                        "format": "table",
                        "minItems": 1,
                        "title": "*ORBAT – FEs used (Inc logistics and enablers)",
                        'items': {
                          "type": "object",
                          'title': "FE",
                          "properties": {
                            "FEName": {
                              "type": "string",
                              'title': "FE Name",
                              "enum": [
                                "Tank",
                                "Infantry",
                                "Plane",
                                "Submarine",
                                "other"
                              ]
                            },
                            "Readiness": {
                              "type": "string",
                              "enum": [
                                "Level-1",
                                "Level-2",
                                "Level-3",
                                "Level-4",
                                "Level-5"
                              ]
                            },
                            "Number": {
                              "type": "number"
                            },
                            'StartDate': {
                              'type': "string",
                              "title": "Start date",
                              "format": "date",
                              "options": {
                                "flatpickr": {
                                  "wrap": false,
                                  "time_24hr": true,
                                  "dateFormat": "d/m/Y"
                                }
                              }
                            },
                            "EndDate": {
                              "type": "string",
                              "title": "End date",
                              "format": "date",
                              "options": {
                                "flatpickr": {
                                  "wrap": false,
                                  "time_24hr": true,
                                  "dateFormat": "d/m/Y"
                                }
                              }
                            }
                          }
                        }
                      },
                      "TIMINGS": {
                        "properties": {
                          "START_PLANNING": {
                            "title": "Start planning",
                            "type": "string",
                            "format": "date",
                            "options": {
                              "flatpickr": {
                                "wrap": false,
                                "time_24hr": true,
                                'dateFormat': "d/m/Y"
                              }
                            }
                          },
                          "START_DEPLOYMENT": {
                            "title": "Start deployment",
                            "type": "string",
                            "format": "date",
                            "options": {
                              "flatpickr": {
                                "wrap": false,
                                "time_24hr": true,
                                "dateFormat": "d/m/Y"
                              }
                            }
                          },
                          "START_OPERATION": {
                            "title": "Start Operation",
                            'type': "string",
                            "format": "date",
                            "options": {
                              "flatpickr": {
                                "wrap": false,
                                "time_24hr": true,
                                "dateFormat": "d/m/Y"
                              }
                            }
                          },
                          "END_OPERATION": {
                            "title": "End Operation",
                            "type": "string",
                            "format": "date",
                            "options": {
                              "flatpickr": {
                                "wrap": false,
                                "time_24hr": true,
                                "dateFormat": "d/m/Y"
                              }
                            }
                          },
                          "END_RECOVERY": {
                            "title": "End recovery",
                            "type": "string",
                            "format": "date",
                            "options": {
                              "flatpickr": {
                                "wrap": false,
                                "time_24hr": true,
                                "dateFormat": "d/m/Y"
                              }
                            }
                          }
                        },
                        "title": "Timings",
                        "type": "object",
                        "format": "grid"
                      },
                      "CONTINUES_INTO_NEXT_TURN": {
                        "type": "boolean",
                        "format": "checkbox",
                        "title": "*Will this activity continue into next turn?",
                        "default": "Yes",
                        "items": {
                          "type": "string",
                          "enum": [
                            "Yes",
                            "No"
                          ]
                        }
                      },
                      "DEPENDENCIES": {
                        "type": "string",
                        "title": "Dependencies on Allied capability: Please indicate which allies (if any) and which of their capabilities you are dependent on. E.g. US Space capabilities, Allied ABO",
                        "format": "textarea"
                      },
                      "AdjudicationSupport": {
                        "type": "array",
                        "format": "checkbox",
                        "title": "Adjudication support",
                        "uniqueItems": true,
                        "items": {
                          "type": "string",
                          "enum": [
                            "Space",
                            "CEMA",
                            "Influence",
                            "Logistics"
                          ]
                        },
                        "options": {
                          "grid_columns": 12
                        }
                      },
                      "PEER_REVIEW": {
                        "type": "string",
                        "title": "Peer Review by",
                        "format": "textarea"
                      },
                      "INSIGHT": {
                        "type": "string",
                        "title": "Insight – What would you have done differently with other policies / permissions / risk appetite?",
                        "format": "textarea"
                      }
                    }
                  },
                  "lastUpdated": '2019-09-30T12:37:26.705Z',
                  "title": 'COA',
                  "_id": 'k16eedkk',
                  "_rev": '1-4c3969d57f8cf470858dd1819ee5c2e8'
                },
                {
                  "lastUpdated": '2019-09-30T12:37:26.705Z',
                  "title": 'RFI',
                  "details": {
                    "format": "grid",
                    "properties": {
                      "Reference": {
                        "readonly": "readonly",
                        "title": "Reference (sys generated)",
                        "options": {
                          "grid_columns": 4
                        },
                        "type": "string"
                      },
                      "Title": {
                        "format": "text",
                        "options": {
                          "grid_columns": 8
                        },
                        "title": "Title",
                        "type": "string"
                      },
                      "RFI": {
                        "format": "textarea",
                        "options": {
                          "grid_columns": 12
                        },
                        "title": "RFI",
                        "type": "string"
                      },
                      "Priority": {
                        "enum": [
                          "High",
                          "Medium",
                          "Low"
                        ],
                        "title": "Priority",
                        "type": "string"
                      },
                      "FAO": {
                        "enum": [
                          "J2",
                          "SME – CEMA",
                          "SME – Space",
                          "SME – Logs & Med",
                          "SME – IO",
                          "SME – White",
                          "Actor – White",
                          "Actor – Red",
                          "Other"
                        ],
                        "title": "FAO",
                        "type": "string"
                      },
                      "ResponseRequiredBy": {
                        "enum": [
                          "Within an hour",
                          "NLT 1300",
                          "NLT 1600",
                          "Not urgent"
                        ],
                        "title": "Response required by",
                        "type": "string"
                      }
                    },
                    "required": [
                      "Reference",
                      "Title",
                      "FAO",
                      "RFI",
                      "Priority",
                      "ResponseRequiredBy"
                    ],
                    "title": "RFI",
                    "type": "object"
                  },
                  "completed": false,
                  "_id": 'k16eedkj',
                  "_rev": '1-683379b9418a2ba688eb4a8dfec4de11'
                },
                {
                  "lastUpdated": '2019-09-30T12:37:26.705Z',
                  "title": 'Message',
                  "details": {
                    "type": 'object',
                    "properties": {
                      "title": {
                        "type": 'string'
                      },
                      "content": {
                        "type": 'string',
                        "format": 'textarea'
                      }
                    },
                    "title": 'Message',
                    "format": 'grid'
                  },
                  "completed": false,
                  "_id": 'k16eedki',
                  "_rev": '1-7de33e447b392eeaf7164f4ec331bc57'
                },
                {
                  "lastUpdated": '2019-09-30T12:37:26.705Z',
                  "title": 'Weather forecast',
                  "details": {
                    "type": 'object',
                    "properties": {
                      "title": {
                        "type": 'string',
                        "title": 'Title'
                      },
                      "Location": {
                        "type": 'object',
                        "properties": {
                          "Lat": {
                            "type": 'number'
                          },
                          'Lat Hemi': {
                            "type": 'string',
                            'enum': [
                              'N',
                              'S'
                            ]
                          },
                          "Long": {
                            "type": 'number'
                          },
                          'Long Hemi': {
                            "type": 'string',
                            'enum': [
                              'E',
                              'W'
                            ]
                          }
                        },
                        "format": 'grid'
                      },
                      'Valid from': {
                        "type": 'string',
                        "format": 'datetime-local',
                        "options": {
                          "flatpickr": {
                            "wrap": true,
                            "time_24hr": true,
                            "allowInput": true
                          }
                        }
                      },
                      'Valid until': {
                        "type": 'string',
                        "format": 'datetime-local',
                        "options": {
                          "flatpickr": {
                            "wrap": true,
                            "time_24hr": true,
                            "allowInput": true
                          }
                        }
                      },
                      "Forecast": {
                        "type": 'string',
                        "format": 'textarea'
                      }
                    },
                    "title": 'Weather Forecast'
                  },
                  "completed": false,
                  "_id": 'k16eedkh',
                  "_rev": '1-f332e0104a371b590346b66dc8e9fa2b'
                },
                {
                  "lastUpdated": '2019-09-30T12:37:26.704Z',
                  "title": 'Machinery failure',
                  "details": {
                    "type": 'object',
                    "properties": {
                      "title": {
                        "type": 'string',
                        "Title": 'Title'
                      },
                      "Date": {
                        "type": 'string',
                        "format": 'datetime-local',
                        "options": {
                          "flatpickr": {
                            "wrap": true,
                            "time_24hr": true,
                            "allowInput": true
                          }
                        }
                      },
                      "Status": {
                        "type": 'string',
                        'enum': [
                          'Minor',
                          'Major',
                          'Critical'
                        ]
                      },
                      "Description": {
                        "type": 'string',
                        'format': 'textarea'
                      }
                    },
                    "title": 'Machinery Failure'
                  },
                  "completed": false,
                  "_id": 'k16eedkg',
                  "_rev": '1-80fc0c1feca8eb6d812d3fa2068ffe89'
                },
                {
                  "completed": false,
                  "details": {
                    "properties": {
                      "Forces": {
                        "format": 'table',
                        "items": {
                          "minItems": 1,
                          "properties": {
                            "assets": {
                              "format": 'table',
                              "items": {
                                "properties": {
                                  'history': {
                                    "format": 'table',
                                    "items": {
                                      "properties": {
                                        "Route": {
                                          "format": 'table',
                                          "items": {
                                            "properties": {
                                              "Location": {
                                                'maxLength': 3,
                                                'type': 'string'
                                              }
                                            }
                                          },
                                          "minItems": 1,
                                          "propertyOrder": 400,
                                          "type": 'array'
                                        },
                                        "Speed": {
                                          "propertyOrder": 300,
                                          'type': 'number'
                                        },
                                        'State': {
                                          'propertyOrder': 200,
                                          'type': 'string'
                                        },
                                        'Turn': {
                                          "propertyOrder": 100,
                                          "type": 'string'
                                        }
                                      }
                                    },
                                    "minItems": 1,
                                    "type": 'array'
                                  },
                                  "name": {
                                    "propertyOrder": 100,
                                    'type': 'string'
                                  },
                                  "planned": {
                                    "format": 'table',
                                    'items': {
                                      "properties": {
                                        "Route": {
                                          'format': 'table',
                                          "items": {
                                            "properties": {
                                              "Location": {
                                                "maxLength": 3,
                                                'type': 'string'
                                              }
                                            }
                                          },
                                          "minItems": 1,
                                          "propertyOrder": 400,
                                          "type": 'array'
                                        },
                                        "Speed": {
                                          "propertyOrder": 300,
                                          'type': 'number'
                                        },
                                        "State": {
                                          "propertyOrder": 200,
                                          "type": 'string'
                                        },
                                        "Turn": {
                                          "propertyOrder": 100,
                                          "type": 'string'
                                        }
                                      }
                                    },
                                    "minItems": 1,
                                    "propertyOrder": 2000,
                                    "type": 'array'
                                  },
                                  "visibleTo": {
                                    "format": 'table',
                                    "items": {
                                      "properties": {
                                        "Force": {
                                          'enum': [
                                            'Blue',
                                            'Red',
                                            'Green'
                                          ],
                                          "type": 'string'
                                        }
                                      }
                                    },
                                    "propertyOrder": 300,
                                    "type": 'array'
                                  }
                                }
                              },
                              "minItems": 1,
                              "type": 'array'
                            },
                            "force": {
                              'enum': [
                                'Blue',
                                'Red',
                                'Green'
                              ],
                              "propertyOrder": 100,
                              "type": 'string'
                            }
                          }
                        },
                        "minItems": 1,
                        "type": 'array'
                      }
                    },
                    "title": 'State of World (Full 2)',
                    "type": 'object'
                  },
                  "lastUpdated": '2019-12-20T15:57:11.519Z',
                  "title": 'State of world (full 2)',
                  "_id": '2019-12-20T15:57:11.519Z',
                  "_rev": '1-4bd7b0b5488182f39f10d5203bb1fad8'
                }
            ]
        }
    },
    "gameTurn": 3,
    "infoType": true,
    "messageType": "InfoMessage",
    "name": "wargame-kzod28lc",
    "phase": "planning",
    "turnEndTime": "2022-02-15T16:55:11+00:00",
    "wargameInitiated": false,
    "wargameTitle": "Small wargame"
}

export default wargame