// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'col': string;
  'head': string;
  'row': string;
}
export const cssExports: CssExports;
export default cssExports;
