// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'assigned': string;
  'badge': string;
  'badges': string;
  'gray': string;
  'green': string;
  'header': string;
  'message-list-wrapper': string;
  'open': string;
  'orange': string;
  'read': string;
  'red': string;
  'rfi-info': string;
  'row': string;
  'status': string;
  'timestamp': string;
}
export const cssExports: CssExports;
export default cssExports;
