// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dropzone-content': string;
  'image-dropzone': string;
}
export const cssExports: CssExports;
export default cssExports;
