// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'checkbox': string;
  'btn': string;
  'input-filter': string;
  'filter-icon': string;
  'light': string;
  'dark': string;
}
export const cssExports: CssExports;
export default cssExports;
