// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'archive-active': string;
  'archive-section': string;
  'btn': string;
  'dark': string;
  'filter-active': string;
  'filter-section': string;
  'light': string;
  'mark-all-as-read-open': string;
  'mark-all-as-read-section': string;
}
export const cssExports: CssExports;
export default cssExports;
