describe('Run_automation_test_Serge', function () {
  const user = cy
  // after(()=>{
  //   user.visit('http://192.168.1.14:8080/serge/admin')
  //   user.inputPassword(pwd).get('.link.link--noIcon').click()
  //   user.clearAllGame()
  // })
  it('Walkthrought_main_cases', function () {
    const roomName = 'This is Cypress Testing_' + Math.floor(Math.random() * 9999)
    const pwd = 'Nelson'

    user.viewport(1280, 688)
    user.clearCookies()
    user.visit('http://192.168.1.14:8080/serge/admin')

    //Input Password 
    user.inputPassword(pwd).get('.link.link--noIcon').click()

    //Overview   
    user.createNewGame()
      .inputRoomName(roomName)
      .clickShowAccessCode()
      .clickSaveOverview()

    //Forces
    user.get('.tab-forces').click()
      .clickAddNew()
      .inputTitleName('Blue')
      .clickAddNewRole()
      .inputRoleName('Media')
      .clickAddNewRoleButton()
      .clickAddNewRole()
      .inputRoleName('Logs')
      .clickAddNewRoleButton()
      .clickSave()

    user.clickAddNew()
      .inputTitleName('Red')
      .chooseColor('#ff4141')
      .clickAddNewRole()
      .inputRoleName('Media')
      .clickAddNewRoleButton()
      .clickAddNewRole()
      .inputRoleName('Logs')
      .clickAddNewRoleButton()
      .clickSave()

    user.chooseForce('White')
      .clickAddNewRole()
      .inputRoleName('Media')
      .clickAddNewRoleButton()
      .clickSave()

    //Channel   
    user.get('.tab-channels')
      .click()
      .clickAddNew()
      .inputTitleName('Red HQ')
      .chooseForceFromDropDown('Red')
      .chooseRoleFromMultiChoose('CO')
      .chooseTemplateFromMultiChoose('Daily intentions')
      .clickCheckButton()
      .chooseForceFromDropDown('White')
      .chooseRoleFromMultiChoose('Game Control')
      .chooseTemplateFromMultiChoose('State of World')
      .clickCheckButton()
      .clickSave()

    user.clickAddNew()
      .inputTitleName('Blue HQ')
      .chooseForceFromDropDown('Blue')
      .chooseRoleFromMultiChoose('CO')
      .chooseTemplateFromMultiChoose('Daily intentions')
      .clickCheckButton()
      .chooseForceFromDropDown('White')
      .chooseRoleFromMultiChoose('Game Control')
      .chooseTemplateFromMultiChoose('State of World')
      .clickCheckButton()
      .clickSave()

    user.clickAddNew()
      .inputTitleName('Blue Chat')
      .chooseForceFromDropDown('Blue')
      .clickCheckButton()
      .clickSave()

    user.clickAddNew()
      .inputTitleName('Red Chat')
      .chooseForceFromDropDown('Red')
      .clickCheckButton()
      .clickSave()

    user.clickAddNew()
      .inputTitleName('Media')
      .chooseForceFromDropDown('White')
      .chooseRoleFromMultiChoose('Media')
      .clickCheckButton()
      .chooseForceFromDropDown('Red')
      .chooseRoleFromMultiChoose('Media')
      .clickCheckButton()
      .chooseForceFromDropDown('Blue')
      .chooseRoleFromMultiChoose('Media')
      .clickCheckButton()
      .clickSave()
  })
})
