// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'footer': string;
  'header': string;
  'modal': string;
  'row': string;
  'select': string;
}
export const cssExports: CssExports;
export default cssExports;
