// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'item': string;
  'item-check': string;
  'item-content': string;
  'item-icon': string;
  'submit': string;
  'title': string;
  'world-state': string;
  'action': string
}
export const cssExports: CssExports;
export default cssExports;
