// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'force-indicator': string;
  'forces-in-channel': string;
  'role-icon': string;
  'mark-all-read': string;
}
export const cssExports: CssExports;
export default cssExports;
