// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chat-message-wrapper': string;
  'chat-message-wrapper__other': string;
  'chat-message-wrapper__owner': string;
  'icon-private': string;
  'info-body': string;
  'info-body__other': string;
  'info-body__owner': string;
  'label-private': string;
  'message-bar': string;
  'message-text': string;
  'private': string;
}
export const cssExports: CssExports;
export default cssExports;
