// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bold': string;
  'float-left': string;
  'float-right': string;
  'info-wrap': string;
  'info-wrap--own-message': string;
  'link': string;
  'message-bullet': string;
  'message-container': string;
  'message-preview-player': string;
  'own-message': string;
  'role': string;
}
export const cssExports: CssExports;
export default cssExports;
