// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bold': string;
  'info-wrap': string;
  'info-wrap--own-message': string;
  'link': string;
  'message-bullet': string;
  'message-preview-player': string;
  'own-message': string;
  'floatRight': string;
  'floatLeft': string;
}
export const cssExports: CssExports;
export default cssExports;
