// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'progress': string;
  'progress-indicator': string;
  'progress-indicator--active': string;
  'progress-indicator--complete': string;
  'scale': string;
}
export const cssExports: CssExports;
export default cssExports;
