// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'rfi-form': string;
  'actions': string;
  'checkbox': string;
}
export const cssExports: CssExports;
export default cssExports;
