// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'force-objectives': string;
  'objective-text': string;
  'role-info': string;
}
export const cssExports: CssExports;
export default cssExports;
