// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cells': string;
  'clip': string;
  'clips': string;
  'input-box': string;
  'list': string;
  'td': string;
}
export const cssExports: CssExports;
export default cssExports;
