// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dark-content': string;
  'light-content': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
