// This file is automatically generated.
// Please do not change this file!
interface CssExports {
<<<<<<< HEAD
=======
  'map': string;
  'map-container': string;
>>>>>>> develop
}
export const cssExports: CssExports;
export default cssExports;
