// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'badge': string;
  'badge-opened': string;
  'btn': string;
  'rfi-form': string;
}
export const cssExports: CssExports;
export default cssExports;
