// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'childnode': string;
  'content': string;
  'header': string;
  'icon': string;
  'infocard': string;
}
export const cssExports: CssExports;
export default cssExports;
