// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue': string;
  'contain-force-skin': string;
  'example': string;
  'force-skin': string;
  'force-type': string;
  'main': string;
  'media': string;
  'message-creator': string;
  'new-message-creator': string;
  'red': string;
  'role-icon': string;
  'role-info': string;
  'role-type': string;
  'send': string;
}
export const cssExports: CssExports;
export default cssExports;
