// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'assigned': string;
  'inset': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
