// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn-send': string;
  'message-creator-wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
