// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'accordion': string;
  'accordion-details': string;
  'accordion-header': string;
  'accordion-sub-title': string;
  'accordion-title': string;
  'accordion-title-group': string;
  'actions': string;
  'arrow-icon': string;
  'box': string;
  'cell-lbl': string;
  'channel-name': string;
  'chat-configuration': string;
  'col': string;
  'col-2': string;
  'configuration': string;
  'constraints-cell': string;
  'constraints-icon': string;
  'control-groups': string;
  'input': string;
  'mapping-item-constraints': string;
  'message-content': string;
  'message-group': string;
  'message-title': string;
  'pager': string;
  'paper-container': string;
  'row': string;
  'section': string;
  'status-item': string;
  'table': string;
  'title': string;
  'channelTabContainer': string;
  'channelTabDetailsContainer': string;
  'mapFieldItem': string;
  'renderersList': string;
  'renderersTab': string;
  'itemTitle': string;
  'participantsTab': string;
  'tableRow': string;
}
export const cssExports: CssExports;
export default cssExports;
