// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon-private': string;
  'label-private': string;
  'private-badge-wrapper': string;
  'wrap-detail': string;
  'wrap-detail-opened': string;
}
export const cssExports: CssExports;
export default cssExports;
