/***
* This file is autogenerated, please do not edit it.
* To generate an updated version, please run `yarn genreg`
***/

export { default as componentSelector } from './component-selector';
export { default as ConditionalWrapper } from './conditional-wrapper';