// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'control': string;
  'control-channel': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
