// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn-cancel': string;
  'insight-form': string;
  'insight-title': string;
}
export const cssExports: CssExports;
export default cssExports;
