// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'attributelist': string;
  'editattributes': string;
  'main': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
