// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'align-center': string;
  'align-justify': string;
  'align-justify-center': string;
  'align-left': string;
  'align-right': string;
  'container': string;
  'disable-offsets': string;
  'group': string;
  'group-title-absolute': string;
  'input': string;
  'main-container': string;
  'select': string;
  'title': string;
  'title-absolute': string;
}
export const cssExports: CssExports;
export default cssExports;
