// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue': string;
  'example': string;
  'green': string;
}
export const cssExports: CssExports;
export default cssExports;
