// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'filterPanel': string;
  'header': string;
  'icon': string;
  'itemsBox': string;
  'itemsPanel': string;
  'panelGroup': string;
  'propertiesPanel': string;
  'resize-handle-horizontal': string;
  'resize-handle-inner': string;
  'resize-handle-outer': string;
}
export const cssExports: CssExports;
export default cssExports;
