// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'filterList': string;
  'filterPanel': string;
  'header': string;
  'icon': string;
  'itemsBox': string;
  'itemsPanel': string;
  'itemsResponsive': string;
  'lblCbx': string;
  'listItem': string;
  'panelGroup': string;
  'propertiesPanel': string;
  'propertiesResponsive': string;
  'removeIcon': string;
  'resize-handle-horizontal': string;
  'resize-handle-inner': string;
  'resize-handle-outer': string;
  'latLng': string
}
export const cssExports: CssExports;
export default cssExports;
