import { INFO_MESSAGE_CLIPPED } from '@serge/config'
import { MessageChannel } from '@serge/custom-types'
import _ from 'lodash'

/** helper function to produce unique ids for channel messages
 */
const getIDs = (message: MessageChannel): string => {
  let res
  if (message.messageType === INFO_MESSAGE_CLIPPED || message.infoType === true || message.message === undefined) {
    res = '' + message.gameTurn
  } else {
    const msg = message.message
    if (msg.Reference !== undefined) {
      // note: `Reference` is the id generated by Serge for Collab-style messages
      res = msg.Reference
    } else {
      res = message._id
    }
  }
  return res
}

/** helper function to reduce the list of messages by removing duplicate
 * turn markers & older versions of messages with reference numbers
 */
const mostRecentOnly = (messages: MessageChannel[]): MessageChannel[] => {
  return _.uniqBy(messages, getIDs)
}
export default mostRecentOnly
