// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'col': string;
  'group': string;
  'hidden': string;
  'label': string;
  'main': string;
  'row': string;
  'section': string;
  'textarea': string;
  'flatpickr': string;
}
export const cssExports: CssExports;
export default cssExports;
