// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'asset-icon-with-image': string;
  'marker-label': string;
  'radius-line': string;
}
export const cssExports: CssExports;
export default cssExports;
