// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'data': string;
  'info-body': string;
  'info-wrap': string;
  'link': string;
  'message-bullet': string;
  'message-list': string;
  'out-of-game-feed': string;
}
export const cssExports: CssExports;
export default cssExports;
