// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'modal': string;
  'modalHeader': string;
  'closeIcon': string;
  'playerLogIcon': string;
  'header': string;
  'title': string;
  'titleMain': string;
  'titleHint': string;
  'content': string;
  'tableContent': string;
  'row': string;
  'header': string;
  'item': string;
  'active': string;
  'inactive': string;
  'loader': string;
}
export const cssExports: CssExports;
export default cssExports;
