// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'orders-panel': string;
  'orders-panel__actions': string;
  'orders-panel__footer': string;
  'orders-panel__header': string;
  'orders-panel__number': string;
  'orders-panel__subtitle': string;
  'orders-panel__title': string;
  'orders-panel__toggler': string;
  'orders-panel__toggler--active': string;
  'slideorders-enter': string;
  'slideorders-enter-active': string;
  'slideorders-leave': string;
  'slideorders-leave-active': string;
}
export const cssExports: CssExports;
export default cssExports;
