// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'data': string;
  'detail': string;
  'detail-row': string;
  'detail-rows': string;
  'icon-private': string;
  'private': string;
  'wrap-detail': string;
  'wrap-detail-opened': string;
  'wrap-private': string;
}
export const cssExports: CssExports;
export default cssExports;
