import React from 'react'
import L from 'leaflet'

// Import component files
import PerceptionForm from './index'
import docs from './README.md'

/* Import mock data */
import { forces, platformTypes } from '@serge/mocks'
import formData from './mocks/formData'
import Mapping from '../mapping'

// import data types
import { Phase } from '@serge/config'

export default {
  title: 'local/PerceptionForm',
  component: PerceptionForm,
  decorators: [],
  parameters: {
    readme: {
      // Show readme before story
      content: docs
    },
    options: {
      // We have no addons enabled in this story, so the addon panel should be hidden
      showPanel: false
    }
  }
}

// put in the post handler
const postback = (messageType: string, payload: any): void => {
  console.log('postback', messageType, payload)
}

const bounds = L.latLngBounds(L.latLng(14.194809302, 42.3558566271), L.latLng(12.401259302, 43.7417816271))

const LocalTileLayer = {
  url: './tiles/{z}/{x}/{y}.png',
  attribution: 'Generated by QTiles'
}

// TODO: Add some state handling here
export const Default: React.FC = () => <Mapping
  tileDiameterMins={5}
  bounds={bounds}
  tileLayer={LocalTileLayer}
  forces={forces}
  wargameInitiated={true}
  playerForce='Blue'
  canSubmitOrders = {true}
  platforms={platformTypes}
  phase={Phase.Adjudication}
  turnNumber={5}
>
  <PerceptionForm mapPostBack={postback} formHeader="Perception header" formData={formData} />
</Mapping>
