// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'asset-icon': string;
  'container': string;
  'health-bar': string;
  'map-container': string;
  'resize-handler': string;
  'slide-container': string;
}
export const cssExports: CssExports;
export default cssExports;
