/* global it expect */

import React from 'react'
import { mount } from 'enzyme'

import HexGrid from './index'
import Mapping from '../mapping'

const bounds = {
  imageTop: 14.194809302,
  imageLeft: 42.3558566271,
  imageRight: 43.7417816271,
  imageBottom: 12.401259302
}

const LocalTileLayer = {
  url: '/tiles/{z}/{x}/{y}.png',
  attribution: 'Generated by QTiles'
}

it('Mapping renders correctly with AssetIcon', () => {
  const div = document.createElement('div')
  document.body.appendChild(div)

  // Using enzyme's 'mount' to solve issues with Leaflet requiring access to the DOM and other features not
  // provided by react.render.
  const tree = mount(<Mapping
    bounds = {bounds}
    tileLayer = {LocalTileLayer}
  ><HexGrid tileSize={0.0416666} width={24} height={21} origin={[14.1166, 42.4166]} /></Mapping>, { attachTo: div })

  expect(tree).toMatchSnapshot()
})
