// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'allowable-hex': string;
  'default-coords': string;
  'default-hex': string;
  'default-hex3': string;
  'num-cells': string;
  'planned-hex': string;
  'planned-line': string;
  'planning-line': string;
  'selected-hex': string;
  'terrain-outline': string;
}
export const cssExports: CssExports;
export default cssExports;
