// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'allowable-hex': string;
  'default-coords': string;
  'default-hex': string;
}
export const cssExports: CssExports;
export default cssExports;
