name: PR

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
  
    name: Build/Test validation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build and Test
        run: |
          # Replace the following command with your actual build and test commands
          yarn build
          yarn test