# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: PR

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: Build/Test [18.x] validation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Change working directory to client folder
        run: cd client

      - name: Running dependency installation
        run: yarn install

      - name: Running project building
        run: yarn build

      - name: Running unit testing
        run: yarn test:unit

      - name: Change working directory to executable folder
        run: cd ../executable

      - name: Running dependency installation
        run: yarn install

      - name: Build executable files
        run: yarn start

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux_executable
          path: /home/runner/work/serge/serge/executable/builds/*_linux.zip
          if-no-files-found: error

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos_executable
          path: /home/runner/work/serge/serge/executable/builds/*_macos.zip
          if-no-files-found: error

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: win64_executable
          path: /home/runner/work/serge/serge/executable/builds/*_win64.zip
          if-no-files-found: error
