# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: PR

on:

  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
  
    name: Build/Test [18.x] validation
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          
      - name : Running dependency installation
        run: yarn install
        
      - name : Running project building
        run: yarn build
        
      - name : Running unit testing
        run: yarn test-unit

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name : Running playwright testing
        run: setsid yarn develop >/dev/null 2>&1 < /dev/null & sleep 1m & yarn test-playwright
        
      - name : Build executable files
        run: yarn pkg-build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux_executable
          path: /home/runner/work/serge/serge/executable/builds/*_linux.zip
          if-no-files-found: error
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos_executable
          path: /home/runner/work/serge/serge/executable/builds/*_macos.zip
          if-no-files-found: error

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: win64_executable
          path: /home/runner/work/serge/serge/executable/builds/*_win64.zip
          if-no-files-found: error
