name: PR and Push

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  test:
    name: Build/Test [18.x] validation
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Running dependency installation for client
        run: cd client && yarn install

      - name: Running project building for client
        run: cd client && yarn build

      - name: Running unit testing for client
        run: cd client && yarn test:unit

      - name: Running dependency installation for executable
        run: cd executable && yarn install

      - name: Running project building for executable
        run: cd executable && yarn start


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux_executable
          path: /home/runner/work/serge/serge/executable/builds/*_linux.zip
          if-no-files-found: error

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos_executable
          path: /home/runner/work/serge/serge/executable/builds/*_macos.zip
          if-no-files-found: error

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: win64_executable
          path: /home/runner/work/serge/serge/executable/builds/*_win64.zip
          if-no-files-found: error
