// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionTab': string;
  'active': string;
  'content': string;
  'panel': string;
  'resize-indicator-container': string;
  'resize-indicator-icon': string;
  'root': string;
  'secondaryActionTab': string;
  'tab-panel': string;
}
export const cssExports: CssExports;
export default cssExports;
