// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'errors': string;
  'footer': string;
  'header': string;
  'modal': string;
  'modalportal': string;
}
export const cssExports: CssExports;
export default cssExports;
