// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'attribute-header': string;
  'button': string;
  'col': string;
  'form-row': string;
  'mobile': string;
  'mobile-title': string;
  'modal': string;
  'row': string;
  'section': string;
  'speedmodalcontent': string;
  'states-holder': string;
  'cell': string;
}
export const cssExports: CssExports;
export default cssExports;
